// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeBaseFieldNames          = builder.RawFieldNames(&KnowledgeBase{})
	knowledgeBaseRows                = strings.Join(knowledgeBaseFieldNames, ",")
	knowledgeBaseRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeBaseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeBaseRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeBaseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgeBaseModel interface {
		Insert(ctx context.Context, data *KnowledgeBase) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*KnowledgeBase, error)
		FindOneByName(ctx context.Context, name string) (*KnowledgeBase, error)
		Update(ctx context.Context, data *KnowledgeBase) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultKnowledgeBaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeBase struct {
		Id               uint64         `db:"id"`                 // 主键ID
		Name             string         `db:"name"`               // 知识库名称
		Description      sql.NullString `db:"description"`        // 知识库描述
		Status           int64          `db:"status"`             // 知识库状态：0-禁用，1-启用
		CreatedAt        time.Time      `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time      `db:"updated_at"`         // 更新时间
		EmbeddingModelId uint64         `db:"embedding_model_id"` // 强绑定 user_api表的embedding模型id,不可修改
		ModelIds         string         `db:"model_ids"`          // 弱绑定, qa/chat/rewrite/rerank模型的id,可修改
	}
)

func newKnowledgeBaseModel(conn sqlx.SqlConn) *defaultKnowledgeBaseModel {
	return &defaultKnowledgeBaseModel{
		conn:  conn,
		table: "`knowledge_base`",
	}
}

func (m *defaultKnowledgeBaseModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKnowledgeBaseModel) FindOne(ctx context.Context, id uint64) (*KnowledgeBase, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeBaseRows, m.table)
	var resp KnowledgeBase
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeBaseModel) FindOneByName(ctx context.Context, name string) (*KnowledgeBase, error) {
	var resp KnowledgeBase
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", knowledgeBaseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeBaseModel) Insert(ctx context.Context, data *KnowledgeBase) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, knowledgeBaseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Status, data.EmbeddingModelId, data.ModelIds)
	return ret, err
}

func (m *defaultKnowledgeBaseModel) Update(ctx context.Context, newData *KnowledgeBase) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowledgeBaseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Description, newData.Status, newData.EmbeddingModelId, newData.ModelIds, newData.Id)
	return err
}

func (m *defaultKnowledgeBaseModel) tableName() string {
	return m.table
}
