// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeDocumentFieldNames          = builder.RawFieldNames(&KnowledgeDocument{})
	knowledgeDocumentRows                = strings.Join(knowledgeDocumentFieldNames, ",")
	knowledgeDocumentRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeDocumentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeDocumentRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeDocumentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgeDocumentModel interface {
		Insert(ctx context.Context, data *KnowledgeDocument) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*KnowledgeDocument, error)
		Update(ctx context.Context, data *KnowledgeDocument) error
		Delete(ctx context.Context, id string) error
	}

	defaultKnowledgeDocumentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeDocument struct {
		Id              string         `db:"id"`                // uuid v7 主键ID
		KnowledgeBaseId uint64         `db:"knowledge_base_id"` // 知识库ID
		DocName         string         `db:"doc_name"`          // 文档名称
		DocType         string         `db:"doc_type"`          // 文档类型(pdf/word/txt)
		StoragePath     string         `db:"storage_path"`      // 文档存储路径
		DocSize         int64          `db:"doc_size"`          // 文档大小（字节）
		Description     sql.NullString `db:"description"`       // 文档描述
		Status          string         `db:"status"`            // 文档状态, disable-禁用, pending-待处理,indexing-索引中, enable-可用, fail-处理失败
		ChunkCount      int64          `db:"chunk_count"`       // 文档分片数量
		ErrMsg          string         `db:"err_msg"`           // 失败原因
		ParserConfig    string         `db:"parser_config"`     // 分词与清洗规则配置
		CreatedAt       time.Time      `db:"created_at"`        // 创建时间
		UpdatedAt       time.Time      `db:"updated_at"`        // 更新时间
	}
)

func newKnowledgeDocumentModel(conn sqlx.SqlConn) *defaultKnowledgeDocumentModel {
	return &defaultKnowledgeDocumentModel{
		conn:  conn,
		table: "`knowledge_document`",
	}
}

func (m *defaultKnowledgeDocumentModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKnowledgeDocumentModel) FindOne(ctx context.Context, id string) (*KnowledgeDocument, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeDocumentRows, m.table)
	var resp KnowledgeDocument
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeDocumentModel) Insert(ctx context.Context, data *KnowledgeDocument) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, knowledgeDocumentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.KnowledgeBaseId, data.DocName, data.DocType, data.StoragePath, data.DocSize, data.Description, data.Status, data.ChunkCount, data.ErrMsg, data.ParserConfig)
	return ret, err
}

func (m *defaultKnowledgeDocumentModel) Update(ctx context.Context, data *KnowledgeDocument) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowledgeDocumentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.KnowledgeBaseId, data.DocName, data.DocType, data.StoragePath, data.DocSize, data.Description, data.Status, data.ChunkCount, data.ErrMsg, data.ParserConfig, data.Id)
	return err
}

func (m *defaultKnowledgeDocumentModel) tableName() string {
	return m.table
}
