// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeDocumentChunkFieldNames          = builder.RawFieldNames(&KnowledgeDocumentChunk{})
	knowledgeDocumentChunkRows                = strings.Join(knowledgeDocumentChunkFieldNames, ",")
	knowledgeDocumentChunkRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeDocumentChunkFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeDocumentChunkRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeDocumentChunkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgeDocumentChunkModel interface {
		Insert(ctx context.Context, data *KnowledgeDocumentChunk) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*KnowledgeDocumentChunk, error)
		Update(ctx context.Context, data *KnowledgeDocumentChunk) error
		Delete(ctx context.Context, id string) error
	}

	defaultKnowledgeDocumentChunkModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeDocumentChunk struct {
		Id                  string    `db:"id"`                    // 分片id-uuid-v7
		KnowledgeBaseId     uint64    `db:"knowledge_base_id"`     // 知识库ID
		KnowledgeDocumentId string    `db:"knowledge_document_id"` // 文档ID
		ChunkText           string    `db:"chunk_text"`            // 分片内容
		ChunkSize           int64     `db:"chunk_size"`            // 分片大小（字节）
		Metadata            string    `db:"metadata"`              // 分片元数据
		CreatedAt           time.Time `db:"created_at"`            // 创建时间
		UpdatedAt           time.Time `db:"updated_at"`            // 更新时间
		Status              string    `db:"status"`                // disable-禁用, enable-启用, qa-正在执行qa生成, embedding-正在生成向量
	}
)

func newKnowledgeDocumentChunkModel(conn sqlx.SqlConn) *defaultKnowledgeDocumentChunkModel {
	return &defaultKnowledgeDocumentChunkModel{
		conn:  conn,
		table: "`knowledge_document_chunk`",
	}
}

func (m *defaultKnowledgeDocumentChunkModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKnowledgeDocumentChunkModel) FindOne(ctx context.Context, id string) (*KnowledgeDocumentChunk, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeDocumentChunkRows, m.table)
	var resp KnowledgeDocumentChunk
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeDocumentChunkModel) Insert(ctx context.Context, data *KnowledgeDocumentChunk) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, knowledgeDocumentChunkRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.KnowledgeBaseId, data.KnowledgeDocumentId, data.ChunkText, data.ChunkSize, data.Metadata, data.Status)
	return ret, err
}

func (m *defaultKnowledgeDocumentChunkModel) Update(ctx context.Context, data *KnowledgeDocumentChunk) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowledgeDocumentChunkRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.KnowledgeBaseId, data.KnowledgeDocumentId, data.ChunkText, data.ChunkSize, data.Metadata, data.Status, data.Id)
	return err
}

func (m *defaultKnowledgeDocumentChunkModel) tableName() string {
	return m.table
}
