// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package chat_message

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatMessageFieldNames          = builder.RawFieldNames(&ChatMessage{})
	chatMessageRows                = strings.Join(chatMessageFieldNames, ",")
	chatMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(chatMessageFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(chatMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	chatMessageModel interface {
		Insert(ctx context.Context, data *ChatMessage) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ChatMessage, error)
		Update(ctx context.Context, data *ChatMessage) error
		Delete(ctx context.Context, id string) error
	}

	defaultChatMessageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChatMessage struct {
		Id               string         `db:"id"`                // 消息ID (UUID)
		ConversationId   string         `db:"conversation_id"`   // 所属会话ID
		SeqId            int64          `db:"seq_id"`            // 消息序号 (用于严格排序)
		Role             string         `db:"role"`              // 角色: user, assistant, system, tool
		Content          string         `db:"content"`           // 消息内容
		ReasoningContent sql.NullString `db:"reasoning_content"` // 深度思考内容 (CoT)
		Type             string         `db:"type"`              // 内容类型: text, json (for tool calls)
		TokenCount       int64          `db:"token_count"`       // Token数量估算
		ToolCallId       sql.NullString `db:"tool_call_id"`      // 工具调用ID
		ExpertMode       int64          `db:"expert_mode"`       // 是否专家模式/深度思考模式
		ModelConfig      sql.NullString `db:"model_config"`      // 当前消息使用的模型配置(Snapshot): model_id, knowledge_base_ids, etc.
		Extra            sql.NullString `db:"extra"`             // 扩展信息: 引用源(citations), 思考过程(reasoning), 耗时等
		CreatedAt        time.Time      `db:"created_at"`        // 创建时间
	}
)

func newChatMessageModel(conn sqlx.SqlConn) *defaultChatMessageModel {
	return &defaultChatMessageModel{
		conn:  conn,
		table: "`chat_message`",
	}
}

func (m *defaultChatMessageModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChatMessageModel) FindOne(ctx context.Context, id string) (*ChatMessage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatMessageRows, m.table)
	var resp ChatMessage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatMessageModel) Insert(ctx context.Context, data *ChatMessage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, chatMessageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ConversationId, data.SeqId, data.Role, data.Content, data.ReasoningContent, data.Type, data.TokenCount, data.ToolCallId, data.ExpertMode, data.ModelConfig, data.Extra)
	return ret, err
}

func (m *defaultChatMessageModel) Update(ctx context.Context, data *ChatMessage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatMessageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.SeqId, data.Role, data.Content, data.ReasoningContent, data.Type, data.TokenCount, data.ToolCallId, data.ExpertMode, data.ModelConfig, data.Extra, data.Id)
	return err
}

func (m *defaultChatMessageModel) tableName() string {
	return m.table
}
