// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package user_api

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userApiFieldNames          = builder.RawFieldNames(&UserApi{})
	userApiRows                = strings.Join(userApiFieldNames, ",")
	userApiRowsExpectAutoSet   = strings.Join(stringx.Remove(userApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userApiRowsWithPlaceHolder = strings.Join(stringx.Remove(userApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserApiIdPrefix                       = "cache:userApi:id:"
	cacheUserApiUserIdModelTypeModelNamePrefix = "cache:userApi:userId:modelType:modelName:"
)

type (
	userApiModel interface {
		Insert(ctx context.Context, data *UserApi) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserApi, error)
		FindOneByUserIdModelTypeModelName(ctx context.Context, userId string, modelType string, modelName string) (*UserApi, error)
		Update(ctx context.Context, data *UserApi) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserApiModel struct {
		sqlc.CachedConn
		table string
	}

	UserApi struct {
		Id          uint64    `db:"id"`          // 主键ID
		UserId      string    `db:"user_id"`     // 用户ID (UUID)
		ConfigName  string    `db:"config_name"` // 配置名称（如：通用问答模型、长文本总结模型）
		ApiKey      string    `db:"api_key"`     // open ai API密钥
		BaseUrl     string    `db:"base_url"`    // 基础请求地址
		ModelName   string    `db:"model_name"`  // 模型名称（如：deepseek-chat、qwen-7b-chat）
		ModelType   string    `db:"model_type"`  // 模型类型（如：chat、embedding、qa、rewrite、rerank）
		ModelDim    int64     `db:"model_dim"`   // 模型向量维度
		MaxTokens   int64     `db:"max_tokens"`  // 单次请求最大tokens数
		Temperature float64   `db:"temperature"` // 温度系数（0-1，控制生成随机性）
		TopP        float64   `db:"top_p"`       // 采样Top-P值
		Timeout     int64     `db:"timeout"`     // 请求超时时间（秒）
		Status      int64     `db:"status"`      // 配置状态：0-禁用，1-启用
		IsDefault   int64     `db:"is_default"`  // 是否为默认配置
		CreatedAt   time.Time `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`  // 更新时间
	}
)

func newUserApiModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserApiModel {
	return &defaultUserApiModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_api`",
	}
}

func (m *defaultUserApiModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userApiIdKey := fmt.Sprintf("%s%v", cacheUserApiIdPrefix, id)
	userApiUserIdModelTypeModelNameKey := fmt.Sprintf("%s%v:%v:%v", cacheUserApiUserIdModelTypeModelNamePrefix, data.UserId, data.ModelType, data.ModelName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userApiIdKey, userApiUserIdModelTypeModelNameKey)
	return err
}

func (m *defaultUserApiModel) FindOne(ctx context.Context, id uint64) (*UserApi, error) {
	userApiIdKey := fmt.Sprintf("%s%v", cacheUserApiIdPrefix, id)
	var resp UserApi
	err := m.QueryRowCtx(ctx, &resp, userApiIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userApiRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserApiModel) FindOneByUserIdModelTypeModelName(ctx context.Context, userId string, modelType string, modelName string) (*UserApi, error) {
	userApiUserIdModelTypeModelNameKey := fmt.Sprintf("%s%v:%v:%v", cacheUserApiUserIdModelTypeModelNamePrefix, userId, modelType, modelName)
	var resp UserApi
	err := m.QueryRowIndexCtx(ctx, &resp, userApiUserIdModelTypeModelNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `model_type` = ? and `model_name` = ? limit 1", userApiRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, modelType, modelName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserApiModel) Insert(ctx context.Context, data *UserApi) (sql.Result, error) {
	userApiIdKey := fmt.Sprintf("%s%v", cacheUserApiIdPrefix, data.Id)
	userApiUserIdModelTypeModelNameKey := fmt.Sprintf("%s%v:%v:%v", cacheUserApiUserIdModelTypeModelNamePrefix, data.UserId, data.ModelType, data.ModelName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userApiRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ConfigName, data.ApiKey, data.BaseUrl, data.ModelName, data.ModelType, data.ModelDim, data.MaxTokens, data.Temperature, data.TopP, data.Timeout, data.Status, data.IsDefault)
	}, userApiIdKey, userApiUserIdModelTypeModelNameKey)
	return ret, err
}

func (m *defaultUserApiModel) Update(ctx context.Context, newData *UserApi) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userApiIdKey := fmt.Sprintf("%s%v", cacheUserApiIdPrefix, data.Id)
	userApiUserIdModelTypeModelNameKey := fmt.Sprintf("%s%v:%v:%v", cacheUserApiUserIdModelTypeModelNamePrefix, data.UserId, data.ModelType, data.ModelName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userApiRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ConfigName, newData.ApiKey, newData.BaseUrl, newData.ModelName, newData.ModelType, newData.ModelDim, newData.MaxTokens, newData.Temperature, newData.TopP, newData.Timeout, newData.Status, newData.IsDefault, newData.Id)
	}, userApiIdKey, userApiUserIdModelTypeModelNameKey)
	return err
}

func (m *defaultUserApiModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserApiIdPrefix, primary)
}

func (m *defaultUserApiModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userApiRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserApiModel) tableName() string {
	return m.table
}
