// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddUserApiReq struct {
	ConfigName  string  `json:"config_name"`                                             // 配置名称
	ApiKey      string  `json:"api_key"`                                                 // API密钥
	BaseUrl     string  `json:"base_url,optional,default=https://api.siliconflow.cn/v1"` // 基础请求地址
	ModelName   string  `json:"model_name"`                                              // 模型名称
	ModelType   string  `json:"model_type"`                                              // 模型类型(chat/embedding/qa/rewrite/rerank)
	ModelDim    int     `json:"model_dim,optional,default=768"`                          // 模型向量维度
	MaxTokens   int     `json:"max_tokens,optional,default=2048"`                        // 单次请求最大tokens数
	Temperature float64 `json:"temperature,optional,default=0.7"`                        // 温度系数(0-1)
	TopP        float64 `json:"top_p,optional,default=0.95"`                             // 采样Top-P值
	Timeout     int     `json:"timeout,optional,default=30"`                             // 请求超时时间(秒)
	Status      int     `json:"status,optional,default=1"`                               // 配置状态:0-禁用,1-启用
	IsDefault   int     `json:"is_default,optional,default=0"`                           // 是否为默认配置
}

type AddUserApiResp struct {
	Id int64 `json:"id"` // 新增配置ID
}

type ChatReq struct {
	ConversationId     string             `json:"conversation_id"`    // 对应 chat_conversation表的id
	Message            string             `json:"message"`            // 用户输入
	ChatModelId        uint64             `json:"chat_model_id"`      // 聊天模型的id, 对应user_api表的id
	Prompt             string             `json:"prompt"`             // 系统提示词
	Temperature        float64            `json:"temperature"`        // 随机性
	KnowledgeBaseIds   []uint64           `json:"knowledge_base_ids"` // 上下文 知识库id列表
	ChatRetrieveConfig ChatRetrieveConfig `json:"chat_retrieve_config"`
}

type ChatResp struct {
	MsgId         string               `json:"msg_id"` // 消息id
	Type          string               `json:"type"`
	Content       string               `json:"content,optional"`
	RetrievalDocs []ChatRetrievalChunk `json:"retrieval_docs,optional"`
	TokenUsage    int                  `json:"token_usage,optional"`
	FinishReason  string               `json:"finish_reason,optional"`
	ErrorMsg      string               `json:"error_msg,optional"`
}

type ChatRetrievalChunk struct {
	ChunkID string  `json:"chunk_id"` // 片段唯一ID
	DocID   string  `json:"doc_id"`   // 所属文档ID
	DocName string  `json:"doc_name"` // 文档名称
	Content string  `json:"content"`  // 片段内容
	Score   float64 `json:"score"`    // 匹配分数
	Source  string  `json:"source"`   // 来源: vector, keyword
}

type ChatRetrieveConfig struct {
	Mode                string  `json:"mode"` // 检索模式：vetcor,fulltext,hybrid
	TopK                int     `json:"top_k"`
	Score               float64 `json:"score"`                // 阈值
	RerankMode          string  `json:"rerank_mode"`          // hybrid模式下的rerank模式: weighted, rerank
	RerankModelId       uint64  `json:"rerank_model_id"`      // rerank模式下,需要传递用户的rerank模型id
	RerankVectorWeight  float64 `json:"rerank_vector_weight"` // weighted模式下, vector的权重 (0-1.0)
	RerankKeywordWeight float64 `json:"rerank_keyword_weight"`
}

type Conversation struct {
	Id           string `json:"id"`
	Title        string `json:"title"`
	MessageCount int    `json:"message_count"`
	UpdatedAt    string `json:"updated_at"`
	CreatedAt    string `json:"created_at"`
}

type CreateKnowledgeBaseReq struct {
	Name        string `json:"name"`                 // 知识库名称
	Description string `json:"description,optional"` // 知识库描述
	EmbeddingId uint64 `json:"embedding_id"`         // 【必填】embedding模型id, 对应user_api表的id
	RerankId    uint64 `json:"rerank_id,optional"`   // 选填，没填就为0
	RewriteId   uint64 `json:"rewrite_id,optional"`  // 选填，没填就为0
	QaId        uint64 `json:"qa_id,optional"`       // 选填，没填就为0
	ChatId      uint64 `json:"chat_id,optional"`     // 选填，没填就为0
}

type CreateKnowledgeBaseResp struct {
	Id int64 `json:"id"`
}

type DeleteAllDocumentReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`
}

type DeleteAllDocumentResp struct {
}

type DeleteConversationReq struct {
	ConversationId string `path:"conversation_id"`
}

type DeleteConversationResp struct {
}

type DeleteKnowledgeBaseReq struct {
	KnowledgeBaseId int64 `path:"knowledge_base_id"`
}

type DeleteKnowledgeBaseResp struct {
}

type DeleteKnowledgeDocumentReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`
	DocumentId      string `path:"document_id"`
}

type DeleteKnowledgeDocumentResp struct {
}

type DeleteUserApiReq struct {
	Id int64 `path:"id"` // 配置ID
}

type DeleteUserApiResp struct {
}

type GetConversationHistoryReq struct {
	ConversationId string `path:"conversation_id"`
}

type GetConversationHistoryResp struct {
	List []HistoryMessage `json:"list"`
}

type GetConversationListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetConversationListResp struct {
	List  []Conversation `json:"list"`
	Total int64          `json:"total"`
}

type GetDocByDocIdReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`
	DocId           string `path:"doc_id"`
}

type GetKnowledgeBaseInfoReq struct {
	KnowledgeBaseId int64 `path:"knowledge_base_id"`
}

type GetKnowledgeBaseListReq struct {
	Page     int   `form:"page,optional,default=1"`
	PageSize int   `form:"page_size,optional,default=10"`
	Status   int64 `form:"status,optional"` // 状态筛选
}

type GetKnowledgeBaseListResp struct {
	Total int64               `json:"total"`
	List  []KnowledgeBaseInfo `json:"list"`
}

type GetKnowledgeDocumentChunksReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`
	DocumentId      string `path:"document_id"`
	Page            int    `form:"page,optional,default=1"`
	PageSize        int    `form:"page_size,optional,default=20"`
}

type GetKnowledgeDocumentChunksResp struct {
	Total int64                        `json:"total"`
	List  []KnowledgeDocumentChunkInfo `json:"list"`
}

type GetKnowledgeDocumentListReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`
	Page            int    `form:"page,optional,default=1"`
	PageSize        int    `form:"page_size,optional,default=10"`
	Status          int    `form:"status,optional"`
}

type GetKnowledgeDocumentListResp struct {
	Total int64                   `json:"total"`
	List  []KnowledgeDocumentInfo `json:"list"`
}

type GetRetrieveLogReq struct {
	Page            int    `form:"page,optional,default=1"`       // 页码
	PageSize        int    `form:"page_size,optional,default=10"` // 每页数量
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`
}

type GetRetrieveLogResp struct {
	Total int64         `json:"total"`
	Logs  []RetrieveLog `json:"logs"`
}

type GetUserApiInfoReq struct {
	Id uint64 `path:"id"` // 对应 user_api.id
}

type GetUserApiListReq struct {
	UserId    int64  `path:"user_id"`
	ModelType string `form:"model_type,optional"`           // 模型类型筛选
	Status    int    `form:"status,optional"`               // 状态筛选:0-禁用,1-启用
	Page      int    `form:"page,optional,default=1"`       // 页码
	PageSize  int    `form:"page_size,optional,default=10"` // 每页数量
}

type GetUserApiListResp struct {
	Total int64         `json:"total"` // 总数
	List  []UserApiInfo `json:"list"`  // 配置列表
}

type GetUserInfoReq struct {
	Id int64 `json:"id"`
}

type GetUserModelReq struct {
	UserId    int64  `path:"user_id"`
	ModelType string `path:"model_type"`
}

type GetUserModelResp struct {
	Total int64         `json:"total"`
	List  []UserApiInfo `json:"list"`
}

type HistoryMessage struct {
	Id            string               `json:"id"`
	Role          string               `json:"role"` // user, assistant
	Content       string               `json:"content"`
	Type          string               `json:"type"` // text
	TokenCount    int                  `json:"token_count"`
	CreatedAt     string               `json:"created_at"`
	RetrievalDocs []ChatRetrievalChunk `json:"retrieval_docs,optional"`
}

type HybridStrategy struct {
	Type          string        `json:"type,optional"`            // 混合策略类型: weighted (加权), rerank (重排序)
	Weights       HybridWeights `json:"weights,optional"`         // 加权模式下的权重配置
	RerankModelID uint64        `json:"rerank_model_id,optional"` // 重排序模式下的模型ID
}

type HybridWeights struct {
	Vector  float64 `json:"vector,optional"`  // 向量检索权重，默认 0.7
	Keyword float64 `json:"keyword,optional"` // 关键词检索权重，默认 0.3
}

type JwtToken struct {
	AccessToken  string `json:"access_token"`  // 核心访问令牌, 鉴权用
	RefreshToken string `json:"refresh_token"` // 刷新令牌, 用于刷新access token
	ExpireAt     int64  `json:"expire_at"`     // access token过期时间，秒级时间戳
	Uid          int64  `json:"uid"`           // 用户ID, 用于前端关联用户信息
}

type KnowledgeBaseInfo struct {
	Id               int64                       `json:"id"`
	Name             string                      `json:"name"`
	Description      string                      `json:"description"`
	Status           int64                       `json:"status"` // 0-禁用，1-启用
	EmbeddingModelId uint64                      `json:"embedding_model_id"`
	ModelIds         []KnowledgeBaseModelIdsInfo `json:"model_ids"` // 知识库用到的模型信息, 默认是 {}
	CreatedAt        string                      `json:"created_at"`
	UpdatedAt        string                      `json:"updated_at"`
}

type KnowledgeBaseModelIdsInfo struct {
	ModelId   uint64 `json:"model_id"`   // user_api表的id
	ModelName string `json:"model_name"` // user_api表的 model_name
	ModelType string `json:"model_type"` // user_api表的 model_type
}

type KnowledgeDocumentChunkInfo struct {
	Id                  string                 `json:"id"`
	KnowledgeBaseId     uint64                 `json:"knowledge_base_id"`
	KnowledgeDocumentId string                 `json:"knowledge_document_id"`
	ChunkText           string                 `json:"chunk_text"`
	ChunkSize           int                    `json:"chunk_size"`
	Metadata            map[string]interface{} `json:"metadata"`
	Status              int                    `json:"status"`
	CreatedAt           string                 `json:"created_at"`
	UpdatedAt           string                 `json:"updated_at"`
}

type KnowledgeDocumentInfo struct {
	Id              string               `json:"id"`
	KnowledgeBaseId uint64               `json:"knowledge_base_id"`
	DocName         string               `json:"doc_name"`
	DocType         string               `json:"doc_type"` // pdf/word/txt
	DocSize         int64                `json:"doc_size"` // 字节
	StoragePath     string               `json:"storage_path"`
	Description     string               `json:"description"`
	Status          string               `json:"status"`      // 文档状态, disable-禁用, pending-待处理,indexing-索引中 ,enable-可用, fail-处理失败
	ChunkCount      int64                `json:"chunk_count"` // 分片数量
	ErrMsg          string               `json:"err_msg"`     // 失败原因
	ParserConfig    SegmentationSettings `json:"parser_config"`
	CreatedAt       string               `json:"created_at"`
	UpdatedAt       string               `json:"updated_at"`
}

type LoginRequest struct {
	Username string `json:"username" example:"lucas"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token JwtToken `json:"token"`
	User  UserInfo `json:"user"`
}

type PreviewChunk struct {
	Index   string `json:"index"`   // 分块序号 Chunk-1
	Content string `json:"content"` // 分块内容
	Length  int    `json:"length"`  // 字符数,UI用于展示 "4 characters"
}

type PreviewChunkReq struct {
	DocId    string               `json:"doc_id"`
	Settings SegmentationSettings `json:"settings"`
}

type PreviewChunkResp struct {
	DocId       string         `json:"doc_id"`
	DocName     string         `json:"doc_name"`
	TotalChunks int            `json:"total_chunks"` // 具体的预览块列表(5-10个块)
	Chunks      []PreviewChunk `json:"chunks"`
	ErrorMsg    string         `json:"error_msg"` // 如果解析失败, 返回该错误信息
}

type RegisterRequest struct {
	Username        string `json:"username"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type RetrievalChunk struct {
	ChunkID string  `json:"chunk_id"` // 片段唯一ID
	DocID   string  `json:"doc_id"`   // 所属文档ID
	DocName string  `json:"doc_name"` // 文档名称
	Content string  `json:"content"`  // 片段内容
	Score   float64 `json:"score"`    // 匹配分数
	Source  string  `json:"source"`   // 来源: vector, keyword
}

type RetrievalConfig struct {
	TopK           int            `json:"top_k,optional,default=10"`            // 返回结果数量
	ScoreThreshold float64        `json:"score_threshold,optional,default=0.6"` // 相似度阈值
	HybridStrategy HybridStrategy `json:"hybrid_strategy,optional"`             // 混合检索策略配置
}

type RetrieveLog struct {
	Id              uint64          `json:"id"` // log id
	KnowledgeBaseId uint64          `json:"knowledge_base_id"`
	Query           string          `json:"query"` // 原始查询
	RetrievalMode   string          `json:"retrieval_mode"`
	RetrievalParams RetrievalConfig `json:"retrieval_params"`
	ChunkCount      int             `json:"chunk_count"`
	TimeCostMs      int64           `json:"time_cost_ms"`
	CreatedAt       string          `json:"created_at"`
}

type RetrieveReq struct {
	KnowledgeBaseId uint64          `path:"knowledge_base_id"`
	Query           string          `json:"query"`                                  // 用户查询语句
	RetrievalMode   string          `json:"retrieval_mode,optional,default=hybrid"` // 检索模式: vector, fulltext, hybrid
	RetrievalConfig RetrievalConfig `json:"retrieval_config,optional"`              // 详细检索配置
	DocIDs          []string        `json:"doc_ids,optional"`                       // 限定检索的文档ID列表
}

type RetrieveResp struct {
	KnowledgeBaseID uint64           `json:"knowledge_base_id"`
	DocIDs          []string         `json:"doc_ids"`      // 涉及的文档ID列表
	TimeCostMs      int64            `json:"time_cost_ms"` // 总检索耗时(ms)
	Chunks          []RetrievalChunk `json:"chunks"`       // 召回结果列表
}

type SaveChunkSettingsReq struct {
	KnowledgeBaseId uint64               `path:"knowledge_base_id"`
	FileIds         []string             `json:"file_ids"`
	Settings        SegmentationSettings `json:"settings"`
}

type SaveChunkSettingsResp struct {
}

type SegmentationPreCleanRule struct {
	CleanWhitespace  bool `json:"clean_whitespace"`   // 替换掉连续的空格、换行符和制表符
	RemoveUrlsEmails bool `json:"remove_urls_emails"` // 删除所有URL和电子邮件地址
}

type SegmentationSettings struct {
	Separators         []string                 `json:"separators"`       // 分割符
	MaxChunkLength     int                      `json:"max_chunk_length"` // 分段最大长度(单位characters)
	ChunkOverlap       int                      `json:"chunk_overlap"`    // 分段重叠长度(单位characters)
	PreCleanRule       SegmentationPreCleanRule `json:"pre_clean_rule"`
	EnableQaGeneration bool                     `json:"enable_qa_generation,default=false"`
}

type SetDefaultModelReq struct {
	UserId    int64  `json:"user_id"`
	ModelId   int64  `json:"model_id"` // 对应user_api表的id
	ModelType string `json:"model_type"`
}

type SetDefaultModelResp struct {
}

type StartNewChatReq struct {
}

type StartNewChatResp struct {
	ConversationId string `json:"conversation_id"`
}

type UpdateConversationReq struct {
	ConversationId string `path:"conversation_id"`
	Title          string `json:"title"`
}

type UpdateConversationResp struct {
}

type UpdateKnowledgeBaseReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`
	Name            string `json:"name,optional"`        // 知识库名称
	Description     string `json:"description,optional"` // 知识库描述
	Status          int64  `json:"status"`               // 状态:0-禁用,1-启用
	RerankId        uint64 `json:"rerank_model_id,optional"`
	RewriteId       uint64 `json:"rewrite_model_id,optional"`
	QaId            uint64 `json:"qa_model_id,optional"`
	ChatId          uint64 `json:"chat_model_id,optional"`
}

type UpdateKnowledgeBaseResp struct {
}

type UploadFileReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`    // 上传到哪个知识库
	Description     string `form:"description,optional"` // 文档描述
}

type UploadFileResp struct {
	Id      int64  `json:"id"`       // 文档ID
	DocName string `json:"doc_name"` // 文档名称
	DocType string `json:"doc_type"` // 文档类型
	DocSize int64  `json:"doc_size"` // 文档大小
}

type UploadMultiFileReq struct {
	KnowledgeBaseId uint64 `path:"knowledge_base_id"`    // 上传到哪个知识库
	Description     string `form:"description,optional"` // 文档描述
}

type UploadMultiFileResp struct {
	FileIds []string `json:"file_ids"` // 上传的文件ID列表
}

type UserApiInfo struct {
	Id          int64   `json:"id"`
	UserId      int64   `json:"user_id"`
	ConfigName  string  `json:"config_name"`
	ApiKey      string  `json:"api_key"`
	BaseUrl     string  `json:"base_url"`
	ModelName   string  `json:"model_name"`
	ModelType   string  `json:"model_type"`
	ModelDim    int     `json:"model_dim"`
	MaxTokens   int     `json:"max_tokens"`
	Temperature float64 `json:"temperature"`
	TopP        float64 `json:"top_p"`
	Timeout     int     `json:"timeout"`
	Status      int     `json:"status"`
	IsDefault   int     `json:"is_default"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type UserInfo struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
}
