// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddTenantLlmReq struct {
	LlmFactory string        `json:"llm_factory"` // 厂商名称
	ApiKey     string        `json:"api_key"`     // 共享的API密钥
	ApiBase    string        `json:"api_base"`    // 共享的API基础地址
	Models     []ModelConfig `json:"models"`      // 要添加的模型列表
}

type AddTenantLlmResp struct {
	SuccessCount int64    `json:"success_count"` // 成功添加数量
	FailedCount  int64    `json:"failed_count"`  // 失败数量
	FailedModels []string `json:"failed_models"` // 失败的模型名称
}

type AddUserApiReq struct {
	ConfigName  string  `json:"config_name"`                                             // 配置名称
	ApiKey      string  `json:"api_key"`                                                 // API密钥
	BaseUrl     string  `json:"base_url,optional,default=https://api.siliconflow.cn/v1"` // 基础请求地址
	ModelName   string  `json:"model_name"`                                              // 模型名称
	ModelType   string  `json:"model_type"`                                              // 模型类型(chat/embedding/qa/rewrite/rerank)
	ModelDim    int     `json:"model_dim,optional,default=768"`                          // 模型向量维度
	MaxTokens   int     `json:"max_tokens,optional,default=2048"`                        // 单次请求最大tokens数
	Temperature float64 `json:"temperature,optional,default=0.7"`                        // 温度系数(0-1)
	TopP        float64 `json:"top_p,optional,default=0.95"`                             // 采样Top-P值
	Timeout     int     `json:"timeout,optional,default=30"`                             // 请求超时时间(秒)
	Status      int     `json:"status,optional,default=1"`                               // 配置状态:0-禁用,1-启用
	IsDefault   int     `json:"is_default,optional,default=0"`                           // 是否为默认配置
}

type AddUserApiResp struct {
	Id int64 `json:"id"` // 新增配置ID
}

type BatchParseDocumentReq struct {
	KnowledgeBaseId string   `json:"knowledge_base_id"` // 知识库ID
	DocumentIds     []string `json:"document_ids"`      // 文档ID列表
}

type BatchParseDocumentResp struct {
}

type ChatReq struct {
	ConversationId     string             `json:"conversation_id"`    // 对应 chat_conversation表的id
	Message            string             `json:"message"`            // 用户输入
	ChatModelId        uint64             `json:"chat_model_id"`      // 聊天模型的id, 对应user_api表的id
	Prompt             string             `json:"prompt"`             // 系统提示词
	Temperature        float64            `json:"temperature"`        // 随机性
	KnowledgeBaseIds   []string           `json:"knowledge_base_ids"` // 上下文 知识库id列表
	ChatRetrieveConfig ChatRetrieveConfig `json:"chat_retrieve_config"`
}

type ChatResp struct {
	MsgId         string               `json:"msg_id"` // 消息id
	Type          string               `json:"type"`
	Content       string               `json:"content,optional"`
	RetrievalDocs []ChatRetrievalChunk `json:"retrieval_docs,optional"`
	TokenUsage    int                  `json:"token_usage,optional"`
	FinishReason  string               `json:"finish_reason,optional"`
	ErrorMsg      string               `json:"error_msg,optional"`
}

type ChatRetrievalChunk struct {
	ChunkID string  `json:"chunk_id"` // 片段唯一ID
	DocID   string  `json:"doc_id"`   // 所属文档ID
	DocName string  `json:"doc_name"` // 文档名称
	Content string  `json:"content"`  // 片段内容
	Score   float64 `json:"score"`    // 匹配分数
	Source  string  `json:"source"`   // 来源: vector, keyword
}

type ChatRetrieveConfig struct {
	Mode                string  `json:"mode"` // 检索模式：vetcor,fulltext,hybrid
	TopK                int     `json:"top_k"`
	Score               float64 `json:"score"`                // 阈值
	RerankMode          string  `json:"rerank_mode"`          // hybrid模式下的rerank模式: weighted, rerank
	RerankModelId       uint64  `json:"rerank_model_id"`      // rerank模式下,需要传递用户的rerank模型id
	RerankVectorWeight  float64 `json:"rerank_vector_weight"` // weighted模式下, vector的权重 (0-1.0)
	RerankKeywordWeight float64 `json:"rerank_keyword_weight"`
}

type ChunkInfo struct {
	Id          string   `json:"id"`
	Content     string   `json:"content"`
	DocId       string   `json:"doc_id"`
	DocName     string   `json:"doc_name"`
	ImportantKw []string `json:"important_keywords"` // 重要关键词
	CreatedAt   float64  `json:"created_at"`         // 创建时间戳
}

type Conversation struct {
	Id           string `json:"id"`
	Title        string `json:"title"`
	MessageCount int    `json:"message_count"`
	UpdatedAt    string `json:"updated_at"`
	CreatedAt    string `json:"created_at"`
}

type CreateInviteReq struct {
	Email string `json:"email"` // 被邀请人邮箱
}

type CreateInviteResp struct {
	InviteCode string `json:"invite_code"` // 邀请码
	InviteLink string `json:"invite_link"` // 邀请链接
}

type CreateKnowledgeBaseReq struct {
	Name                   string  `json:"name"`
	Avatar                 string  `json:"avatar,optional"`
	Language               string  `json:"language,optional,default=Chinese"`
	Description            string  `json:"description,optional"`
	EmbdId                 string  `json:"embd_id"`
	Permission             string  `json:"permission,optional,default=me"`
	SimilarityThreshold    float64 `json:"similarity_threshold,optional,default=0.3"`
	VectorSimilarityWeight float64 `json:"vector_similarity_weight,optional,default=0.3"`
}

type CreateKnowledgeBaseResp struct {
	KnowledgeBaseInfo
}

type DeleteConversationReq struct {
	ConversationId string `path:"conversation_id"`
}

type DeleteConversationResp struct {
}

type DeleteKnowledgeBaseReq struct {
	Id string `path:"id"`
}

type DeleteKnowledgeBaseResp struct {
}

type DeleteKnowledgeDocumentReq struct {
	Id string `path:"id"`
}

type DeleteKnowledgeDocumentResp struct {
}

type DeleteTenantLlmReq struct {
	Id int64 `path:"id"`
}

type DeleteUserApiReq struct {
	Id int64 `path:"id"` // 配置ID
}

type DeleteUserApiResp struct {
}

type GetConversationHistoryReq struct {
	ConversationId string `path:"conversation_id"`
}

type GetConversationHistoryResp struct {
	List []HistoryMessage `json:"list"`
}

type GetConversationListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetConversationListResp struct {
	List  []Conversation `json:"list"`
	Total int64          `json:"total"`
}

type GetKnowledgeBaseReq struct {
	Id string `path:"id"`
}

type GetKnowledgeBaseResp struct {
	KnowledgeBaseInfo
}

type GetKnowledgeDocumentReq struct {
	Id string `path:"id"`
}

type GetKnowledgeDocumentResp struct {
	KnowledgeDocumentInfo
}

type GetRetrieveLogReq struct {
	Page            int    `form:"page,optional,default=1"`       // 页码
	PageSize        int    `form:"page_size,optional,default=10"` // 每页数量
	KnowledgeBaseId string `path:"knowledge_base_id"`
}

type GetRetrieveLogResp struct {
	Total int64         `json:"total"`
	Logs  []RetrieveLog `json:"logs"`
}

type GetUserApiInfoReq struct {
	Id uint64 `path:"id"` // 对应 user_api.id
}

type GetUserApiListReq struct {
	UserId    string `path:"user_id"`                       // 用户ID (UUID)
	ModelType string `form:"model_type,optional"`           // 模型类型筛选
	Status    int    `form:"status,optional"`               // 状态筛选:0-禁用,1-启用
	Page      int    `form:"page,optional,default=1"`       // 页码
	PageSize  int    `form:"page_size,optional,default=10"` // 每页数量
}

type GetUserApiListResp struct {
	Total int64         `json:"total"` // 总数
	List  []UserApiInfo `json:"list"`  // 配置列表
}

type GetUserInfoReq struct {
	Id string `json:"id,optional"` // 用户ID (UUID), 可选，不传则查询当前登录用户
}

type GetUserModelReq struct {
	UserId    string `path:"user_id"` // 用户ID (UUID)
	ModelType string `path:"model_type"`
}

type GetUserModelResp struct {
	Total int64         `json:"total"`
	List  []UserApiInfo `json:"list"`
}

type HistoryMessage struct {
	Id            string               `json:"id"`
	Role          string               `json:"role"` // user, assistant
	Content       string               `json:"content"`
	Type          string               `json:"type"` // text
	TokenCount    int                  `json:"token_count"`
	CreatedAt     string               `json:"created_at"`
	RetrievalDocs []ChatRetrievalChunk `json:"retrieval_docs,optional"`
}

type HybridStrategy struct {
	Type          string        `json:"type,optional"`            // 混合策略类型: weighted (加权), rerank (重排序)
	Weights       HybridWeights `json:"weights,optional"`         // 加权模式下的权重配置
	RerankModelID uint64        `json:"rerank_model_id,optional"` // 重排序模式下的模型ID
}

type HybridWeights struct {
	Vector  float64 `json:"vector,optional"`  // 向量检索权重，默认 0.7
	Keyword float64 `json:"keyword,optional"` // 关键词检索权重，默认 0.3
}

type JoinTeamReq struct {
	InviteCode string `json:"invite_code"` // 邀请码
}

type JoinTeamResp struct {
	Success bool `json:"success"`
}

type JoinedTeam struct {
	TenantId   string `json:"tenant_id"`
	TenantName string `json:"tenant_name"`
	OwnerName  string `json:"owner_name"`
	Role       string `json:"role"`
	JoinedTime int64  `json:"joined_time"`
}

type JwtToken struct {
	AccessToken  string `json:"access_token"`  // 核心访问令牌, 鉴权用
	RefreshToken string `json:"refresh_token"` // 刷新令牌, 用于刷新access token
	ExpireAt     int64  `json:"expire_at"`     // access token过期时间，秒级时间戳
}

type KnowledgeBaseInfo struct {
	Id                     string  `json:"id"`
	Avatar                 string  `json:"avatar,optional"`
	TenantId               string  `json:"tenant_id"`
	Name                   string  `json:"name"`
	Language               string  `json:"language"`
	Description            string  `json:"description,optional"`
	EmbdId                 string  `json:"embd_id"`
	Permission             string  `json:"permission"`
	CreatedBy              string  `json:"created_by"`
	DocNum                 int64   `json:"doc_num"`
	TokenNum               int64   `json:"token_num"`
	ChunkNum               int64   `json:"chunk_num"`
	SimilarityThreshold    float64 `json:"similarity_threshold"`
	VectorSimilarityWeight float64 `json:"vector_similarity_weight"`
	Status                 int64   `json:"status"`
	ParserId               string  `json:"parser_id"`     // 解析器ID
	ParserConfig           string  `json:"parser_config"` // 解析配置 JSON
	CreatedTime            int64   `json:"created_time"`
	UpdatedTime            int64   `json:"updated_time"`
}

type KnowledgeDocumentInfo struct {
	Id              string  `json:"id"`
	KnowledgeBaseId string  `json:"knowledge_base_id"`
	DocName         string  `json:"doc_name"`
	DocType         string  `json:"doc_type"`
	DocSize         int64   `json:"doc_size"`
	StoragePath     string  `json:"storage_path"`
	Description     string  `json:"description"`
	Status          int64   `json:"status"`
	RunStatus       string  `json:"run_status"`
	ChunkNum        int64   `json:"chunk_num"`
	TokenNum        int64   `json:"token_num"`
	ParserConfig    string  `json:"parser_config"` // JSON string
	Progress        float64 `json:"progress"`
	ProgressMsg     string  `json:"progress_msg"`
	CreatedBy       string  `json:"created_by"`
	CreatedTime     int64   `json:"created_time"`
	UpdatedTime     int64   `json:"updated_time"`
}

type ListJoinedTeamsResp struct {
	List []JoinedTeam `json:"list"`
}

type ListKnowledgeBaseReq struct {
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"page_size,optional,default=20"`
	Keyword  string `form:"keyword,optional"`
}

type ListKnowledgeBaseResp struct {
	Total int64               `json:"total"`
	List  []KnowledgeBaseInfo `json:"list"`
}

type ListKnowledgeDocumentChunksReq struct {
	Id              string `path:"id"`                            // 文档ID
	KnowledgeBaseId string `form:"knowledge_base_id"`             // 知识库ID
	Page            int64  `form:"page,optional,default=1"`       // 页码
	PageSize        int64  `form:"page_size,optional,default=20"` // 每页条数
	Keyword         string `form:"keyword,optional"`              // 搜索切片内容
}

type ListKnowledgeDocumentChunksResp struct {
	Total int64       `json:"total"`
	List  []ChunkInfo `json:"list"`
}

type ListKnowledgeDocumentReq struct {
	KnowledgeBaseId string `form:"knowledge_base_id"`
	Page            int64  `form:"page,optional,default=1"`
	PageSize        int64  `form:"page_size,optional,default=20"`
	Keyword         string `form:"keyword,optional"`
}

type ListKnowledgeDocumentResp struct {
	Total int64                   `json:"total"`
	List  []KnowledgeDocumentInfo `json:"list"`
}

type ListLlmFactoriesReq struct {
}

type ListLlmFactoriesResp struct {
	List []LlmFactoryInfo `json:"list"`
}

type ListMembersResp struct {
	List []TeamMember `json:"list"`
}

type ListTenantLlmGroupedResp struct {
	List []TenantLlmGroupByFactory `json:"list"`
}

type ListTenantLlmReq struct {
	LlmFactory string `form:"llm_factory,optional"` // 按厂商筛选
	ModelType  string `form:"model_type,optional"`  // 按类型筛选
	Status     int64  `form:"status,optional"`      // 按状态筛选
	Page       int64  `form:"page,optional,default=1"`
	PageSize   int64  `form:"page_size,optional,default=20"`
}

type ListTenantLlmResp struct {
	Total int64           `json:"total"`
	List  []TenantLlmInfo `json:"list"`
}

type LlmFactoryInfo struct {
	Name    string   `json:"name"`
	Logo    string   `json:"logo"`
	Tags    string   `json:"tags"`     // 逗号分隔的模型类型
	TagList []string `json:"tag_list"` // 拆分后的类型数组
	Rank    int64    `json:"rank"`
	Status  int64    `json:"status"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token         JwtToken     `json:"token"`
	User          UserInfo     `json:"user"`
	CurrentTenant TenantInfo   `json:"current_tenant"` // 当前活跃租户
	Tenants       []TenantInfo `json:"tenants"`        // 用户关联的所有租户
}

type ModelConfig struct {
	ModelType string `json:"model_type"` // LLM, Embedding, Rerank, ...
	LlmName   string `json:"llm_name"`   // 模型名称
	MaxTokens int64  `json:"max_tokens,optional,default=8192"`
}

type RegisterRequest struct {
	Nickname        string `json:"nickname"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type RetrievalChunk struct {
	ChunkID string  `json:"chunk_id"` // 片段唯一ID
	DocID   string  `json:"doc_id"`   // 所属文档ID
	DocName string  `json:"doc_name"` // 文档名称
	Content string  `json:"content"`  // 片段内容
	Score   float64 `json:"score"`    // 匹配分数
	Source  string  `json:"source"`   // 来源: vector, keyword
}

type RetrievalConfig struct {
	TopK           int            `json:"top_k,optional,default=10"`            // 返回结果数量
	ScoreThreshold float64        `json:"score_threshold,optional,default=0.6"` // 相似度阈值
	HybridStrategy HybridStrategy `json:"hybrid_strategy,optional"`             // 混合检索策略配置
}

type RetrieveLog struct {
	Id              uint64          `json:"id"` // log id
	KnowledgeBaseId string          `json:"knowledge_base_id"`
	Query           string          `json:"query"` // 原始查询
	RetrievalMode   string          `json:"retrieval_mode"`
	RetrievalParams RetrievalConfig `json:"retrieval_params"`
	ChunkCount      int             `json:"chunk_count"`
	TimeCostMs      int64           `json:"time_cost_ms"`
	CreatedAt       string          `json:"created_at"`
}

type RetrieveReq struct {
	KnowledgeBaseId string          `path:"knowledge_base_id"`
	Query           string          `json:"query"`                                  // 用户查询语句
	RetrievalMode   string          `json:"retrieval_mode,optional,default=hybrid"` // 检索模式: vector, fulltext, hybrid
	RetrievalConfig RetrievalConfig `json:"retrieval_config,optional"`              // 详细检索配置
	DocIDs          []string        `json:"doc_ids,optional"`                       // 限定检索的文档ID列表
}

type RetrieveResp struct {
	KnowledgeBaseID string           `json:"knowledge_base_id"`
	DocIDs          []string         `json:"doc_ids"`      // 涉及的文档ID列表
	TimeCostMs      int64            `json:"time_cost_ms"` // 总检索耗时(ms)
	Chunks          []RetrievalChunk `json:"chunks"`       // 召回结果列表
}

type RetryDocumentReq struct {
	Id string `path:"id"`
}

type RetryDocumentResp struct {
}

type SetDefaultModelReq struct {
	UserId    string `json:"user_id"`  // 用户ID (UUID)
	ModelId   int64  `json:"model_id"` // 对应user_api表的id
	ModelType string `json:"model_type"`
}

type SetDefaultModelResp struct {
}

type StartNewChatReq struct {
}

type StartNewChatResp struct {
	ConversationId string `json:"conversation_id"`
}

type TeamMember struct {
	UserId     string `json:"user_id"`
	Nickname   string `json:"nickname"`
	Email      string `json:"email"`
	Role       string `json:"role"`        // owner | admin | member
	Status     int64  `json:"status"`      // 1-有效, 0-禁用
	JoinedTime int64  `json:"joined_time"` // 加入时间戳(ms)
}

type TenantInfo struct {
	TenantId string `json:"tenant_id"`
	Name     string `json:"name"`
	Role     string `json:"role"` // owner|admin|member
}

type TenantLlmGroupByFactory struct {
	LlmFactory  string          `json:"llm_factory"`
	FactoryLogo string          `json:"factory_logo"`
	ApiBase     string          `json:"api_base"`
	Models      []TenantLlmInfo `json:"models"`
}

type TenantLlmInfo struct {
	Id          int64  `json:"id"`
	TenantId    string `json:"tenant_id"`
	LlmFactory  string `json:"llm_factory"`
	ModelType   string `json:"model_type"`
	LlmName     string `json:"llm_name"`
	ApiKey      string `json:"api_key"` // 返回时脱敏处理
	ApiBase     string `json:"api_base"`
	MaxTokens   int64  `json:"max_tokens"`
	UsedTokens  int64  `json:"used_tokens"`
	Status      int64  `json:"status"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type UpdateConversationReq struct {
	ConversationId string `path:"conversation_id"`
	Title          string `json:"title"`
}

type UpdateConversationResp struct {
}

type UpdateDocumentParserConfigReq struct {
	Id           string `path:"id"`
	ParserConfig string `json:"parser_config"` // JSON string
}

type UpdateDocumentParserConfigResp struct {
}

type UpdateKnowledgeBasePermissionReq struct {
	Id         string `path:"id"`
	Permission string `json:"permission"` // me | team
}

type UpdateKnowledgeBasePermissionResp struct {
}

type UpdateKnowledgeBaseReq struct {
	Id                     string  `path:"id"`
	Name                   string  `json:"name,optional"`
	Avatar                 string  `json:"avatar,optional"`
	Language               string  `json:"language,optional"`
	Description            string  `json:"description,optional"`
	Permission             string  `json:"permission,optional"`
	SimilarityThreshold    float64 `json:"similarity_threshold,optional"`
	VectorSimilarityWeight float64 `json:"vector_similarity_weight,optional"`
	Status                 int64   `json:"status,optional"`
	ParserId               string  `json:"parser_id,optional"`     // 解析器ID: general | resume
	ParserConfig           string  `json:"parser_config,optional"` // 解析配置 JSON
}

type UpdateKnowledgeBaseResp struct {
}

type UpdateTenantLlmReq struct {
	Id        int64  `path:"id"`
	ApiKey    string `json:"api_key,optional"`
	ApiBase   string `json:"api_base,optional"`
	MaxTokens int64  `json:"max_tokens,optional"`
	Status    int64  `json:"status,optional"`
}

type UploadDocumentReq struct {
	KnowledgeBaseId string `form:"knowledge_base_id"`
}

type UploadDocumentResp struct {
	FileIds []string           `json:"file_ids"` // 文件ID列表
	Files   []UploadedFileInfo `json:"files"`    // 文件详细信息列表
}

type UploadedFileInfo struct {
	Id      string `json:"id"`
	DocName string `json:"doc_name"`
}

type UserApiInfo struct {
	Id          int64   `json:"id"`
	UserId      string  `json:"user_id"` // 用户ID (UUID)
	ConfigName  string  `json:"config_name"`
	ApiKey      string  `json:"api_key"`
	BaseUrl     string  `json:"base_url"`
	ModelName   string  `json:"model_name"`
	ModelType   string  `json:"model_type"`
	ModelDim    int     `json:"model_dim"`
	MaxTokens   int     `json:"max_tokens"`
	Temperature float64 `json:"temperature"`
	TopP        float64 `json:"top_p"`
	Timeout     int     `json:"timeout"`
	Status      int     `json:"status"`
	IsDefault   int     `json:"is_default"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type UserInfo struct {
	UserId   string `json:"user_id"` // UUID v7
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar,optional"`
	Language string `json:"language,optional"`
}

type VerifyInviteReq struct {
	Code string `path:"code"` // 邀请码
}

type VerifyInviteResp struct {
	TenantId   string `json:"tenant_id"`   // 租户ID
	TenantName string `json:"tenant_name"` // 租户名称
	Inviter    string `json:"inviter"`     // 邀请人昵称
}
