// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package llm

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	llmFieldNames          = builder.RawFieldNames(&Llm{})
	llmRows                = strings.Join(llmFieldNames, ",")
	llmRowsExpectAutoSet   = strings.Join(stringx.Remove(llmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	llmRowsWithPlaceHolder = strings.Join(stringx.Remove(llmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLlmIdPrefix         = "cache:llm:id:"
	cacheLlmFidLlmNamePrefix = "cache:llm:fid:llmName:"
)

type (
	llmModel interface {
		Insert(ctx context.Context, data *Llm) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Llm, error)
		FindOneByFidLlmName(ctx context.Context, fid string, llmName string) (*Llm, error)
		Update(ctx context.Context, data *Llm) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLlmModel struct {
		sqlc.CachedConn
		table string
	}

	Llm struct {
		Id          int64     `db:"id"`           // 自增主键
		LlmName     string    `db:"llm_name"`     // LLM模型名称
		ModelType   string    `db:"model_type"`   // 模型类型: LLM, Text Embedding, Image2Text, ASR
		Fid         string    `db:"fid"`          // LLM厂商ID
		MaxTokens   int64     `db:"max_tokens"`   // 最大Token数
		Tags        string    `db:"tags"`         // 标签: LLM, Text Embedding, Image2Text, Chat, 32k...
		IsTools     int64     `db:"is_tools"`     // 是否支持工具调用
		Status      int64     `db:"status"`       // 状态: 0-废弃, 1-有效
		CreatedTime int64     `db:"created_time"` // 创建时间戳
		UpdatedTime int64     `db:"updated_time"` // 更新时间戳
		CreatedDate time.Time `db:"created_date"` // 创建日期
		UpdatedDate time.Time `db:"updated_date"` // 更新日期
	}
)

func newLlmModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLlmModel {
	return &defaultLlmModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`llm`",
	}
}

func (m *defaultLlmModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	llmFidLlmNameKey := fmt.Sprintf("%s%v:%v", cacheLlmFidLlmNamePrefix, data.Fid, data.LlmName)
	llmIdKey := fmt.Sprintf("%s%v", cacheLlmIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, llmFidLlmNameKey, llmIdKey)
	return err
}

func (m *defaultLlmModel) FindOne(ctx context.Context, id int64) (*Llm, error) {
	llmIdKey := fmt.Sprintf("%s%v", cacheLlmIdPrefix, id)
	var resp Llm
	err := m.QueryRowCtx(ctx, &resp, llmIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", llmRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLlmModel) FindOneByFidLlmName(ctx context.Context, fid string, llmName string) (*Llm, error) {
	llmFidLlmNameKey := fmt.Sprintf("%s%v:%v", cacheLlmFidLlmNamePrefix, fid, llmName)
	var resp Llm
	err := m.QueryRowIndexCtx(ctx, &resp, llmFidLlmNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `fid` = ? and `llm_name` = ? limit 1", llmRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, fid, llmName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLlmModel) Insert(ctx context.Context, data *Llm) (sql.Result, error) {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动填充时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()
	nowUnix := now.UnixMilli()
	// 直接赋值 int64，不需要 sql.NullInt64
	data.CreatedTime = nowUnix
	data.UpdatedTime = nowUnix

	// 直接赋值 time.Time，不需要 sql.NullTime
	data.CreatedDate = now
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	llmFidLlmNameKey := fmt.Sprintf("%s%v:%v", cacheLlmFidLlmNamePrefix, data.Fid, data.LlmName)
	llmIdKey := fmt.Sprintf("%s%v", cacheLlmIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, llmRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.LlmName, data.ModelType, data.Fid, data.MaxTokens, data.Tags, data.IsTools, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate)
	}, llmFidLlmNameKey, llmIdKey)
	return ret, err
}

func (m *defaultLlmModel) Update(ctx context.Context, newData *Llm) error {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动更新时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()

	// 直接赋值，Update 操作只需更新 update_xxx 字段
	newData.UpdatedTime = now.UnixMilli()
	newData.UpdatedDate = now
	// --------------------------------------------------------------------------------

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	llmFidLlmNameKey := fmt.Sprintf("%s%v:%v", cacheLlmFidLlmNamePrefix, data.Fid, data.LlmName)
	llmIdKey := fmt.Sprintf("%s%v", cacheLlmIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, llmRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.LlmName, newData.ModelType, newData.Fid, newData.MaxTokens, newData.Tags, newData.IsTools, newData.Status, newData.CreatedTime, newData.UpdatedTime, newData.CreatedDate, newData.UpdatedDate, newData.Id)
	}, llmFidLlmNameKey, llmIdKey)
	return err
}

func (m *defaultLlmModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLlmIdPrefix, primary)
}

func (m *defaultLlmModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", llmRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLlmModel) tableName() string {
	return m.table
}
