// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package tenant_llm

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tenantLlmFieldNames          = builder.RawFieldNames(&TenantLlm{})
	tenantLlmRows                = strings.Join(tenantLlmFieldNames, ",")
	tenantLlmRowsExpectAutoSet   = strings.Join(stringx.Remove(tenantLlmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tenantLlmRowsWithPlaceHolder = strings.Join(stringx.Remove(tenantLlmFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTenantLlmIdPrefix                        = "cache:tenantLlm:id:"
	cacheTenantLlmTenantIdLlmFactoryLlmNamePrefix = "cache:tenantLlm:tenantId:llmFactory:llmName:"
)

type (
	tenantLlmModel interface {
		Insert(ctx context.Context, data *TenantLlm) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TenantLlm, error)
		FindOneByTenantIdLlmFactoryLlmName(ctx context.Context, tenantId string, llmFactory string, llmName string) (*TenantLlm, error)
		Update(ctx context.Context, data *TenantLlm) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTenantLlmModel struct {
		sqlc.CachedConn
		table string
	}

	TenantLlm struct {
		Id          uint64         `db:"id"`           // 自增主键
		TenantId    string         `db:"tenant_id"`    // 租户ID
		LlmFactory  string         `db:"llm_factory"`  // LLM厂商名称
		ModelType   sql.NullString `db:"model_type"`   // 模型类型: LLM, Text Embedding, Image2Text, ASR
		LlmName     string         `db:"llm_name"`     // LLM模型名称
		ApiKey      sql.NullString `db:"api_key"`      // API密钥
		ApiBase     sql.NullString `db:"api_base"`     // API基础地址
		MaxTokens   int64          `db:"max_tokens"`   // 最大Token数
		UsedTokens  int64          `db:"used_tokens"`  // 已使用Token数
		Status      int64          `db:"status"`       // 状态: 0-废弃, 1-有效
		CreatedTime int64          `db:"created_time"` // 创建时间戳
		UpdatedTime int64          `db:"updated_time"` // 更新时间戳
		CreatedDate time.Time      `db:"created_date"` // 创建日期
		UpdatedDate time.Time      `db:"updated_date"` // 更新日期
	}
)

func newTenantLlmModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTenantLlmModel {
	return &defaultTenantLlmModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tenant_llm`",
	}
}

func (m *defaultTenantLlmModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tenantLlmIdKey := fmt.Sprintf("%s%v", cacheTenantLlmIdPrefix, id)
	tenantLlmTenantIdLlmFactoryLlmNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTenantLlmTenantIdLlmFactoryLlmNamePrefix, data.TenantId, data.LlmFactory, data.LlmName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tenantLlmIdKey, tenantLlmTenantIdLlmFactoryLlmNameKey)
	return err
}

func (m *defaultTenantLlmModel) FindOne(ctx context.Context, id uint64) (*TenantLlm, error) {
	tenantLlmIdKey := fmt.Sprintf("%s%v", cacheTenantLlmIdPrefix, id)
	var resp TenantLlm
	err := m.QueryRowCtx(ctx, &resp, tenantLlmIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tenantLlmRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTenantLlmModel) FindOneByTenantIdLlmFactoryLlmName(ctx context.Context, tenantId string, llmFactory string, llmName string) (*TenantLlm, error) {
	tenantLlmTenantIdLlmFactoryLlmNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTenantLlmTenantIdLlmFactoryLlmNamePrefix, tenantId, llmFactory, llmName)
	var resp TenantLlm
	err := m.QueryRowIndexCtx(ctx, &resp, tenantLlmTenantIdLlmFactoryLlmNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `llm_factory` = ? and `llm_name` = ? limit 1", tenantLlmRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, llmFactory, llmName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTenantLlmModel) Insert(ctx context.Context, data *TenantLlm) (sql.Result, error) {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动填充时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()
	nowUnix := now.UnixMilli()
	// 直接赋值 int64，不需要 sql.NullInt64
	data.CreatedTime = nowUnix
	data.UpdatedTime = nowUnix

	// 直接赋值 time.Time，不需要 sql.NullTime
	data.CreatedDate = now
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	tenantLlmIdKey := fmt.Sprintf("%s%v", cacheTenantLlmIdPrefix, data.Id)
	tenantLlmTenantIdLlmFactoryLlmNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTenantLlmTenantIdLlmFactoryLlmNamePrefix, data.TenantId, data.LlmFactory, data.LlmName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tenantLlmRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.LlmFactory, data.ModelType, data.LlmName, data.ApiKey, data.ApiBase, data.MaxTokens, data.UsedTokens, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate)
	}, tenantLlmIdKey, tenantLlmTenantIdLlmFactoryLlmNameKey)
	return ret, err
}

func (m *defaultTenantLlmModel) Update(ctx context.Context, newData *TenantLlm) error {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动更新时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()

	// 直接赋值，Update 操作只需更新 update_xxx 字段
	newData.UpdatedTime = now.UnixMilli()
	newData.UpdatedDate = now
	// --------------------------------------------------------------------------------

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tenantLlmIdKey := fmt.Sprintf("%s%v", cacheTenantLlmIdPrefix, data.Id)
	tenantLlmTenantIdLlmFactoryLlmNameKey := fmt.Sprintf("%s%v:%v:%v", cacheTenantLlmTenantIdLlmFactoryLlmNamePrefix, data.TenantId, data.LlmFactory, data.LlmName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tenantLlmRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.LlmFactory, newData.ModelType, newData.LlmName, newData.ApiKey, newData.ApiBase, newData.MaxTokens, newData.UsedTokens, newData.Status, newData.CreatedTime, newData.UpdatedTime, newData.CreatedDate, newData.UpdatedDate, newData.Id)
	}, tenantLlmIdKey, tenantLlmTenantIdLlmFactoryLlmNameKey)
	return err
}

func (m *defaultTenantLlmModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTenantLlmIdPrefix, primary)
}

func (m *defaultTenantLlmModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tenantLlmRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTenantLlmModel) tableName() string {
	return m.table
}
