// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package local_message

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	localMessageFieldNames          = builder.RawFieldNames(&LocalMessage{})
	localMessageRows                = strings.Join(localMessageFieldNames, ",")
	localMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(localMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	localMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(localMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	localMessageModel interface {
		Insert(ctx context.Context, data *LocalMessage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*LocalMessage, error)
		Update(ctx context.Context, data *LocalMessage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultLocalMessageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LocalMessage struct {
		Id            uint64         `db:"id"`              // 主键ID
		TaskType      string         `db:"task_type"`       // 任务类型, document_index | graph_extraction
		ReqSnapshot   string         `db:"req_snapshot"`    // 请求快照 json
		Status        string         `db:"status"`          // 状态, init | fail | success
		NextRetryTime int64          `db:"next_retry_time"` // 下一次重试时间
		RetryTimes    int64          `db:"retry_times"`     // 已经重试次数
		MaxRetryTimes int64          `db:"max_retry_times"` // 最大重试次数
		FailReason    sql.NullString `db:"fail_reason"`     // 执行失败的信息
		CreatedAt     time.Time      `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time      `db:"updated_at"`      // 更新时间
		Deleted       int64          `db:"deleted"`         // 删除标记
	}
)

func newLocalMessageModel(conn sqlx.SqlConn) *defaultLocalMessageModel {
	return &defaultLocalMessageModel{
		conn:  conn,
		table: "`local_message`",
	}
}

func (m *defaultLocalMessageModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLocalMessageModel) FindOne(ctx context.Context, id uint64) (*LocalMessage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", localMessageRows, m.table)
	var resp LocalMessage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLocalMessageModel) Insert(ctx context.Context, data *LocalMessage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, localMessageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TaskType, data.ReqSnapshot, data.Status, data.NextRetryTime, data.RetryTimes, data.MaxRetryTimes, data.FailReason, data.Deleted)
	return ret, err
}

func (m *defaultLocalMessageModel) Update(ctx context.Context, data *LocalMessage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, localMessageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TaskType, data.ReqSnapshot, data.Status, data.NextRetryTime, data.RetryTimes, data.MaxRetryTimes, data.FailReason, data.Deleted, data.Id)
	return err
}

func (m *defaultLocalMessageModel) tableName() string {
	return m.table
}
