// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package knowledge_base

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeBaseFieldNames          = builder.RawFieldNames(&KnowledgeBase{})
	knowledgeBaseRows                = strings.Join(knowledgeBaseFieldNames, ",")
	knowledgeBaseRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeBaseFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeBaseRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeBaseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKnowledgeBaseIdPrefix           = "cache:knowledgeBase:id:"
	cacheKnowledgeBaseTenantIdNamePrefix = "cache:knowledgeBase:tenantId:name:"
)

type (
	knowledgeBaseModel interface {
		Insert(ctx context.Context, data *KnowledgeBase) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*KnowledgeBase, error)
		FindOneByTenantIdName(ctx context.Context, tenantId string, name string) (*KnowledgeBase, error)
		Update(ctx context.Context, data *KnowledgeBase) error
		Delete(ctx context.Context, id string) error
	}

	defaultKnowledgeBaseModel struct {
		sqlc.CachedConn
		table string
	}

	KnowledgeBase struct {
		Id                     string         `db:"id"`                       // 主键ID, UUID v7
		Avatar                 sql.NullString `db:"avatar"`                   // 知识库头像 base64
		TenantId               string         `db:"tenant_id"`                // 所属租户ID, 核心隔离字段
		Name                   string         `db:"name"`                     // 知识库名称
		Language               string         `db:"language"`                 // 语言: English|Chinese, 影响分词策略
		Description            sql.NullString `db:"description"`              // 描述
		EmbdId                 string         `db:"embd_id"`                  // Embedding模型ID (来自租户配置)
		Permission             string         `db:"permission"`               // 权限: me(仅创建者)|team(租户全员)
		CreatedBy              string         `db:"created_by"`               // 创建者用户ID
		DocNum                 uint64         `db:"doc_num"`                  // 文档数量
		TokenNum               uint64         `db:"token_num"`                // Token总数
		ChunkNum               uint64         `db:"chunk_num"`                // 分片总数
		SimilarityThreshold    float64        `db:"similarity_threshold"`     // 检索相似度阈值
		VectorSimilarityWeight float64        `db:"vector_similarity_weight"` // 混合检索向量权重 (1-keyword)
		Status                 int64          `db:"status"`                   // 状态: 1-启用, 0-禁用
		ParserId               string         `db:"parser_id"`                // 解析器ID,目前仅支持 general | resume
		ParserConfig           sql.NullString `db:"parser_config"`            // 解析器配置, 默认是 {}
		CreatedTime            int64          `db:"created_time"`             // 创建时间戳(ms)
		UpdatedTime            int64          `db:"updated_time"`             // 更新时间戳(ms)
		CreatedDate            time.Time      `db:"created_date"`             // 创建日期
		UpdatedDate            time.Time      `db:"updated_date"`             // 更新日期
	}
)

func newKnowledgeBaseModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultKnowledgeBaseModel {
	return &defaultKnowledgeBaseModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`knowledge_base`",
	}
}

func (m *defaultKnowledgeBaseModel) Delete(ctx context.Context, id string) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	knowledgeBaseIdKey := fmt.Sprintf("%s%v", cacheKnowledgeBaseIdPrefix, id)
	knowledgeBaseTenantIdNameKey := fmt.Sprintf("%s%v:%v", cacheKnowledgeBaseTenantIdNamePrefix, data.TenantId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, knowledgeBaseIdKey, knowledgeBaseTenantIdNameKey)
	return err
}

func (m *defaultKnowledgeBaseModel) FindOne(ctx context.Context, id string) (*KnowledgeBase, error) {
	knowledgeBaseIdKey := fmt.Sprintf("%s%v", cacheKnowledgeBaseIdPrefix, id)
	var resp KnowledgeBase
	err := m.QueryRowCtx(ctx, &resp, knowledgeBaseIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeBaseRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeBaseModel) FindOneByTenantIdName(ctx context.Context, tenantId string, name string) (*KnowledgeBase, error) {
	knowledgeBaseTenantIdNameKey := fmt.Sprintf("%s%v:%v", cacheKnowledgeBaseTenantIdNamePrefix, tenantId, name)
	var resp KnowledgeBase
	err := m.QueryRowIndexCtx(ctx, &resp, knowledgeBaseTenantIdNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `name` = ? limit 1", knowledgeBaseRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeBaseModel) Insert(ctx context.Context, data *KnowledgeBase) (sql.Result, error) {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动填充时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()
	nowUnix := now.UnixMilli()
	// 直接赋值 int64，不需要 sql.NullInt64
	data.CreatedTime = nowUnix
	data.UpdatedTime = nowUnix

	// 直接赋值 time.Time，不需要 sql.NullTime
	data.CreatedDate = now
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	knowledgeBaseIdKey := fmt.Sprintf("%s%v", cacheKnowledgeBaseIdPrefix, data.Id)
	knowledgeBaseTenantIdNameKey := fmt.Sprintf("%s%v:%v", cacheKnowledgeBaseTenantIdNamePrefix, data.TenantId, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, knowledgeBaseRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Avatar, data.TenantId, data.Name, data.Language, data.Description, data.EmbdId, data.Permission, data.CreatedBy, data.DocNum, data.TokenNum, data.ChunkNum, data.SimilarityThreshold, data.VectorSimilarityWeight, data.Status, data.ParserId, data.ParserConfig, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate)
	}, knowledgeBaseIdKey, knowledgeBaseTenantIdNameKey)
	return ret, err
}

func (m *defaultKnowledgeBaseModel) Update(ctx context.Context, newData *KnowledgeBase) error {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动更新时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()

	// 直接赋值，Update 操作只需更新 update_xxx 字段
	newData.UpdatedTime = now.UnixMilli()
	newData.UpdatedDate = now
	// --------------------------------------------------------------------------------

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	knowledgeBaseIdKey := fmt.Sprintf("%s%v", cacheKnowledgeBaseIdPrefix, data.Id)
	knowledgeBaseTenantIdNameKey := fmt.Sprintf("%s%v:%v", cacheKnowledgeBaseTenantIdNamePrefix, data.TenantId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowledgeBaseRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Avatar, newData.TenantId, newData.Name, newData.Language, newData.Description, newData.EmbdId, newData.Permission, newData.CreatedBy, newData.DocNum, newData.TokenNum, newData.ChunkNum, newData.SimilarityThreshold, newData.VectorSimilarityWeight, newData.Status, newData.ParserId, newData.ParserConfig, newData.CreatedTime, newData.UpdatedTime, newData.CreatedDate, newData.UpdatedDate, newData.Id)
	}, knowledgeBaseIdKey, knowledgeBaseTenantIdNameKey)
	return err
}

func (m *defaultKnowledgeBaseModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKnowledgeBaseIdPrefix, primary)
}

func (m *defaultKnowledgeBaseModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeBaseRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultKnowledgeBaseModel) tableName() string {
	return m.table
}
