// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package tenant

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tenantFieldNames          = builder.RawFieldNames(&Tenant{})
	tenantRows                = strings.Join(tenantFieldNames, ",")
	tenantRowsExpectAutoSet   = strings.Join(stringx.Remove(tenantFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tenantRowsWithPlaceHolder = strings.Join(stringx.Remove(tenantFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTenantIdPrefix = "cache:tenant:id:"
)

type (
	tenantModel interface {
		Insert(ctx context.Context, data *Tenant) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Tenant, error)
		Update(ctx context.Context, data *Tenant) error
		Delete(ctx context.Context, id string) error
	}

	defaultTenantModel struct {
		sqlc.CachedConn
		table string
	}

	Tenant struct {
		Id          string         `db:"id"`           // 租户ID
		Name        sql.NullString `db:"name"`         // 租户名称
		LlmId       string         `db:"llm_id"`       // 默认LLM模型ID
		EmbdId      string         `db:"embd_id"`      // 默认Embedding模型ID
		AsrId       string         `db:"asr_id"`       // 默认ASR模型ID
		Img2txtId   string         `db:"img2txt_id"`   // 默认图片转文字模型ID
		RerankId    string         `db:"rerank_id"`    // 默认重排序模型ID
		TtsId       string         `db:"tts_id"`       // 默认TTS模型ID
		ParserIds   string         `db:"parser_ids"`   // 文档处理器列表
		Credit      int64          `db:"credit"`       // 积分
		Status      int64          `db:"status"`       // 状态: 1=正常, 0=禁用
		CreatedTime int64          `db:"created_time"` // 创建时间戳
		UpdatedTime int64          `db:"updated_time"` // 更新时间戳
		CreatedDate time.Time      `db:"created_date"` // 创建日期
		UpdatedDate time.Time      `db:"updated_date"` // 更新日期
	}
)

func newTenantModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTenantModel {
	return &defaultTenantModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tenant`",
	}
}

func (m *defaultTenantModel) Delete(ctx context.Context, id string) error {
	tenantIdKey := fmt.Sprintf("%s%v", cacheTenantIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tenantIdKey)
	return err
}

func (m *defaultTenantModel) FindOne(ctx context.Context, id string) (*Tenant, error) {
	tenantIdKey := fmt.Sprintf("%s%v", cacheTenantIdPrefix, id)
	var resp Tenant
	err := m.QueryRowCtx(ctx, &resp, tenantIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tenantRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTenantModel) Insert(ctx context.Context, data *Tenant) (sql.Result, error) {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动填充时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()
	nowUnix := now.UnixMilli()
	// 直接赋值 int64，不需要 sql.NullInt64
	data.CreatedTime = nowUnix
	data.UpdatedTime = nowUnix

	// 直接赋值 time.Time，不需要 sql.NullTime
	data.CreatedDate = now
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	tenantIdKey := fmt.Sprintf("%s%v", cacheTenantIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tenantRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.LlmId, data.EmbdId, data.AsrId, data.Img2txtId, data.RerankId, data.TtsId, data.ParserIds, data.Credit, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate)
	}, tenantIdKey)
	return ret, err
}

func (m *defaultTenantModel) Update(ctx context.Context, data *Tenant) error {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动更新时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()

	// 直接赋值，Update 操作只需更新 update_xxx 字段
	data.UpdatedTime = now.UnixMilli()
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	tenantIdKey := fmt.Sprintf("%s%v", cacheTenantIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tenantRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.LlmId, data.EmbdId, data.AsrId, data.Img2txtId, data.RerankId, data.TtsId, data.ParserIds, data.Credit, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate, data.Id)
	}, tenantIdKey)
	return err
}

func (m *defaultTenantModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTenantIdPrefix, primary)
}

func (m *defaultTenantModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tenantRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTenantModel) tableName() string {
	return m.table
}
