// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package chat_conversation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatConversationFieldNames          = builder.RawFieldNames(&ChatConversation{})
	chatConversationRows                = strings.Join(chatConversationFieldNames, ",")
	chatConversationRowsExpectAutoSet   = strings.Join(stringx.Remove(chatConversationFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatConversationRowsWithPlaceHolder = strings.Join(stringx.Remove(chatConversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChatConversationIdPrefix = "cache:chatConversation:id:"
)

type (
	chatConversationModel interface {
		Insert(ctx context.Context, data *ChatConversation) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ChatConversation, error)
		Update(ctx context.Context, data *ChatConversation) error
		Delete(ctx context.Context, id string) error
	}

	defaultChatConversationModel struct {
		sqlc.CachedConn
		table string
	}

	ChatConversation struct {
		Id           string         `db:"id"`            // 会话ID (UUID)
		UserId       string         `db:"user_id"`       // 用户ID (UUID)
		TenantId     string         `db:"tenant_id"`     // 租户ID (UUID)
		Title        string         `db:"title"`         // 会话标题
		Status       int64          `db:"status"`        // 状态: 1-正常, 2-归档, 3-删除
		Config       sql.NullString `db:"config"`        // 对话配置: llm_id, system_prompt, etc.
		MessageCount int64          `db:"message_count"` // 消息数量
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newChatConversationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultChatConversationModel {
	return &defaultChatConversationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`chat_conversation`",
	}
}

func (m *defaultChatConversationModel) Delete(ctx context.Context, id string) error {
	chatConversationIdKey := fmt.Sprintf("%s%v", cacheChatConversationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, chatConversationIdKey)
	return err
}

func (m *defaultChatConversationModel) FindOne(ctx context.Context, id string) (*ChatConversation, error) {
	chatConversationIdKey := fmt.Sprintf("%s%v", cacheChatConversationIdPrefix, id)
	var resp ChatConversation
	err := m.QueryRowCtx(ctx, &resp, chatConversationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatConversationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatConversationModel) Insert(ctx context.Context, data *ChatConversation) (sql.Result, error) {
	chatConversationIdKey := fmt.Sprintf("%s%v", cacheChatConversationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, chatConversationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.TenantId, data.Title, data.Status, data.Config, data.MessageCount)
	}, chatConversationIdKey)
	return ret, err
}

func (m *defaultChatConversationModel) Update(ctx context.Context, data *ChatConversation) error {
	chatConversationIdKey := fmt.Sprintf("%s%v", cacheChatConversationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatConversationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.TenantId, data.Title, data.Status, data.Config, data.MessageCount, data.Id)
	}, chatConversationIdKey)
	return err
}

func (m *defaultChatConversationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChatConversationIdPrefix, primary)
}

func (m *defaultChatConversationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatConversationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChatConversationModel) tableName() string {
	return m.table
}
