// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	chat "gozero-rag/restful/rag/internal/handler/chat"
	knowledge "gozero-rag/restful/rag/internal/handler/knowledge"
	login "gozero-rag/restful/rag/internal/handler/login"
	retrieval "gozero-rag/restful/rag/internal/handler/retrieval"
	user "gozero-rag/restful/rag/internal/handler/user"
	"gozero-rag/restful/rag/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// sse对话
				Method:  http.MethodPost,
				Path:    "/chat/sse",
				Handler: chat.ChatHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取会话列表
				Method:  http.MethodGet,
				Path:    "/chat/conversations",
				Handler: chat.GetConversationListHandler(serverCtx),
			},
			{
				// 删除会话
				Method:  http.MethodDelete,
				Path:    "/chat/conversations/:conversation_id",
				Handler: chat.DeleteConversationHandler(serverCtx),
			},
			{
				// 更新会话标题
				Method:  http.MethodPut,
				Path:    "/chat/conversations/:conversation_id",
				Handler: chat.UpdateConversationHandler(serverCtx),
			},
			{
				// 获取会话历史消息
				Method:  http.MethodGet,
				Path:    "/chat/conversations/:conversation_id/messages",
				Handler: chat.GetConversationHistoryHandler(serverCtx),
			},
			{
				// 开启新对话,返回一个 会话id
				Method:  http.MethodPost,
				Path:    "/chat/new",
				Handler: chat.StartNewChatHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建知识库
				Method:  http.MethodPost,
				Path:    "/knowledge",
				Handler: knowledge.CreateKnowledgeBaseHandler(serverCtx),
			},
			{
				// 删除知识库
				Method:  http.MethodDelete,
				Path:    "/knowledge/:knowledge_base_id",
				Handler: knowledge.DeleteKnowledgeBaseHandler(serverCtx),
			},
			{
				// 获取知识库详情
				Method:  http.MethodGet,
				Path:    "/knowledge/:knowledge_base_id",
				Handler: knowledge.GetKnowledgeBaseInfoHandler(serverCtx),
			},
			{
				// 修改知识库(描述信息、启用或禁用状态、知识库名称）
				Method:  http.MethodPut,
				Path:    "/knowledge/:knowledge_base_id",
				Handler: knowledge.UpdateKnowledgeBaseHandler(serverCtx),
			},
			{
				// 获取指定知识库、指定文档的所有分片
				Method:  http.MethodGet,
				Path:    "/knowledge/:knowledge_base_id/:document_id/chunks",
				Handler: knowledge.GetKnowledgeDocumentChunksHandler(serverCtx),
			},
			{
				// 删除知识库的所有文档(状态不是indexing的都删掉）
				Method:  http.MethodDelete,
				Path:    "/knowledge/:knowledge_base_id/all",
				Handler: knowledge.DeleteAllDocsHandler(serverCtx),
			},
			{
				// 保存分片配置
				Method:  http.MethodPost,
				Path:    "/knowledge/:knowledge_base_id/document/chunk/save",
				Handler: knowledge.SaveChunkSettingsHandler(serverCtx),
			},
			{
				// 查看分片效果
				Method:  http.MethodPost,
				Path:    "/knowledge/:knowledge_base_id/document/preview",
				Handler: knowledge.PreviewChunkHandler(serverCtx),
			},
			{
				// 获取指定文档的信息
				Method:  http.MethodGet,
				Path:    "/knowledge/:knowledge_base_id/get_document/:doc_id",
				Handler: knowledge.GetDocByDocIdHandler(serverCtx),
			},
			{
				// 根据知识库id,获取知识库的文档列表
				Method:  http.MethodGet,
				Path:    "/knowledge/:knowledge_base_id/list",
				Handler: knowledge.GetKnowledgeDocumentListHandler(serverCtx),
			},
			{
				// 上传 pdf/txt/docx 文件到指定知识库，使用 multipart/form-data，文件字段名: file
				Method:  http.MethodPost,
				Path:    "/knowledge/:knowledge_base_id/upload",
				Handler: knowledge.UploadFileHandler(serverCtx),
			},
			{
				// 上传多个文件到指定知识库 ，文件字段名: files
				Method:  http.MethodPost,
				Path:    "/knowledge/:knowledge_base_id/uploadmulti",
				Handler: knowledge.UploadMultiFileHandler(serverCtx),
			},
			{
				// 获取知识库列表
				Method:  http.MethodGet,
				Path:    "/knowledge/list",
				Handler: knowledge.GetKnowledgeBaseListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: login.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: login.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 知识库召回测试
				Method:  http.MethodPost,
				Path:    "/retrieval/:knowledge_base_id",
				Handler: retrieval.GetRetrievalHandler(serverCtx),
			},
			{
				// 获取知识库召回记录
				Method:  http.MethodGet,
				Path:    "/retrieval/log/:knowledge_base_id",
				Handler: retrieval.GetRetrievalLogHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 添加用户API配置
				Method:  http.MethodPost,
				Path:    "/user/api",
				Handler: user.AddUserApiHandler(serverCtx),
			},
			{
				// 删除用户API配置
				Method:  http.MethodDelete,
				Path:    "/user/api/:id",
				Handler: user.DeleteUserApiHandler(serverCtx),
			},
			{
				// 获取用户模型列表
				Method:  http.MethodGet,
				Path:    "/user/api/:user_id",
				Handler: user.GetUserApiListHandler(serverCtx),
			},
			{
				// 获取指定类型的模型
				Method:  http.MethodGet,
				Path:    "/user/api/:user_id/:model_type",
				Handler: user.GetUserApiByModelTypeHandler(serverCtx),
			},
			{
				// 获取模型信息
				Method:  http.MethodGet,
				Path:    "/user/api/detail/:id",
				Handler: user.GetUserApiInfoHandler(serverCtx),
			},
			{
				// 将模型设为默认模型
				Method:  http.MethodPost,
				Path:    "/user/api/set_default",
				Handler: user.SetDefaultModelHandler(serverCtx),
			},
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
