// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	chat "gozero-rag/restful/rag/internal/handler/chat"
	graph "gozero-rag/restful/rag/internal/handler/graph"
	knowledge_base "gozero-rag/restful/rag/internal/handler/knowledge_base"
	knowledge_document "gozero-rag/restful/rag/internal/handler/knowledge_document"
	llm_factories "gozero-rag/restful/rag/internal/handler/llm_factories"
	login "gozero-rag/restful/rag/internal/handler/login"
	retrieval "gozero-rag/restful/rag/internal/handler/retrieval"
	team "gozero-rag/restful/rag/internal/handler/team"
	tenant_llm "gozero-rag/restful/rag/internal/handler/tenant_llm"
	user "gozero-rag/restful/rag/internal/handler/user"
	"gozero-rag/restful/rag/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// sse对话
				Method:  http.MethodPost,
				Path:    "/chat/sse",
				Handler: chat.ChatHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取会话列表
				Method:  http.MethodGet,
				Path:    "/chat/conversations",
				Handler: chat.GetConversationListHandler(serverCtx),
			},
			{
				// 删除会话
				Method:  http.MethodDelete,
				Path:    "/chat/conversations/:conversation_id",
				Handler: chat.DeleteConversationHandler(serverCtx),
			},
			{
				// 更新会话标题
				Method:  http.MethodPut,
				Path:    "/chat/conversations/:conversation_id",
				Handler: chat.UpdateConversationHandler(serverCtx),
			},
			{
				// 获取会话历史消息
				Method:  http.MethodGet,
				Path:    "/chat/conversations/:conversation_id/messages",
				Handler: chat.GetConversationHistoryHandler(serverCtx),
			},
			{
				// 开启新对话,返回一个 会话id
				Method:  http.MethodPost,
				Path:    "/chat/new",
				Handler: chat.StartNewChatHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取知识图谱数据
				Method:  http.MethodGet,
				Path:    "/:kb_id/graph",
				Handler: graph.GetKnowledgeGraphHandler(serverCtx),
			},
			{
				// 搜索图谱节点
				Method:  http.MethodGet,
				Path:    "/:kb_id/graph/search",
				Handler: graph.SearchKnowledgeGraphHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/knowledge"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取知识库详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: knowledge_base.GetKnowledgeBaseHandler(serverCtx),
			},
			{
				// 更新知识库
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: knowledge_base.UpdateKnowledgeBaseHandler(serverCtx),
			},
			{
				// 删除知识库
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: knowledge_base.DeleteKnowledgeBaseHandler(serverCtx),
			},
			{
				// 删除知识库下的所有文档
				Method:  http.MethodDelete,
				Path:    "/:id/all",
				Handler: knowledge_base.DeleteAllDocumentHandler(serverCtx),
			},
			{
				// 更新知识库权限
				Method:  http.MethodPatch,
				Path:    "/:id/permission",
				Handler: knowledge_base.UpdateKnowledgeBasePermissionHandler(serverCtx),
			},
			{
				// 创建知识库
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: knowledge_base.CreateKnowledgeBaseHandler(serverCtx),
			},
			{
				// 获取知识库列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: knowledge_base.ListKnowledgeBaseHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/knowledge"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取文档列表
				Method:  http.MethodGet,
				Path:    "/knowledge_document",
				Handler: knowledge_document.ListKnowledgeDocumentHandler(serverCtx),
			},
			{
				// 获取文档详情
				Method:  http.MethodGet,
				Path:    "/knowledge_document/:id",
				Handler: knowledge_document.GetKnowledgeDocumentHandler(serverCtx),
			},
			{
				// 删除文档
				Method:  http.MethodDelete,
				Path:    "/knowledge_document/:id",
				Handler: knowledge_document.DeleteKnowledgeDocumentHandler(serverCtx),
			},
			{
				// 获取文档切片列表
				Method:  http.MethodGet,
				Path:    "/knowledge_document/:id/chunks",
				Handler: knowledge_document.ListKnowledgeDocumentChunksHandler(serverCtx),
			},
			{
				// 更新文档解析配置
				Method:  http.MethodPut,
				Path:    "/knowledge_document/:id/parser_config",
				Handler: knowledge_document.UpdateDocumentParserConfigHandler(serverCtx),
			},
			{
				// 重试/重新解析文档
				Method:  http.MethodPost,
				Path:    "/knowledge_document/:id/retry",
				Handler: knowledge_document.RetryDocumentHandler(serverCtx),
			},
			{
				// 批量解析文档
				Method:  http.MethodPost,
				Path:    "/knowledge_document/batch_parse",
				Handler: knowledge_document.BatchParseDocumentHandler(serverCtx),
			},
			{
				// 上传文档
				Method:  http.MethodPost,
				Path:    "/knowledge_document/upload",
				Handler: knowledge_document.UploadDocumentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取系统支持的LLM厂商列表
				Method:  http.MethodGet,
				Path:    "/llm/factories",
				Handler: llm_factories.ListLlmFactoriesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: login.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: login.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 知识库召回测试
				Method:  http.MethodPost,
				Path:    "/retrieval/:knowledge_base_id",
				Handler: retrieval.GetRetrievalHandler(serverCtx),
			},
			{
				// 获取知识库召回记录
				Method:  http.MethodGet,
				Path:    "/retrieval/log/:knowledge_base_id",
				Handler: retrieval.GetRetrievalLogHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发起邀请
				Method:  http.MethodPost,
				Path:    "/team/invite",
				Handler: team.CreateInviteHandler(serverCtx),
			},
			{
				// 验证邀请码信息
				Method:  http.MethodGet,
				Path:    "/team/invite/:code",
				Handler: team.VerifyInviteHandler(serverCtx),
			},
			{
				// 使用邀请码加入团队
				Method:  http.MethodPost,
				Path:    "/team/join",
				Handler: team.JoinTeamHandler(serverCtx),
			},
			{
				// 获取我加入的团队列表
				Method:  http.MethodGet,
				Path:    "/team/joined",
				Handler: team.ListJoinedTeamsHandler(serverCtx),
			},
			{
				// 获取当前团队成员列表
				Method:  http.MethodGet,
				Path:    "/team/members",
				Handler: team.ListMembersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 批量添加租户LLM配置
				Method:  http.MethodPost,
				Path:    "/tenant/llm",
				Handler: tenant_llm.AddTenantLlmHandler(serverCtx),
			},
			{
				// 获取租户LLM配置列表
				Method:  http.MethodGet,
				Path:    "/tenant/llm",
				Handler: tenant_llm.ListTenantLlmHandler(serverCtx),
			},
			{
				// 更新租户LLM配置
				Method:  http.MethodPut,
				Path:    "/tenant/llm/:id",
				Handler: tenant_llm.UpdateTenantLlmHandler(serverCtx),
			},
			{
				// 删除租户LLM配置
				Method:  http.MethodDelete,
				Path:    "/tenant/llm/:id",
				Handler: tenant_llm.DeleteTenantLlmHandler(serverCtx),
			},
			{
				// 获取租户LLM配置列表(按厂商分组)
				Method:  http.MethodGet,
				Path:    "/tenant/llm/grouped",
				Handler: tenant_llm.ListTenantLlmGroupedHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 添加用户API配置
				Method:  http.MethodPost,
				Path:    "/user/api",
				Handler: user.AddUserApiHandler(serverCtx),
			},
			{
				// 删除用户API配置
				Method:  http.MethodDelete,
				Path:    "/user/api/:id",
				Handler: user.DeleteUserApiHandler(serverCtx),
			},
			{
				// 获取用户模型列表
				Method:  http.MethodGet,
				Path:    "/user/api/:user_id",
				Handler: user.GetUserApiListHandler(serverCtx),
			},
			{
				// 获取指定类型的模型
				Method:  http.MethodGet,
				Path:    "/user/api/:user_id/:model_type",
				Handler: user.GetUserApiByModelTypeHandler(serverCtx),
			},
			{
				// 获取模型信息
				Method:  http.MethodGet,
				Path:    "/user/api/detail/:id",
				Handler: user.GetUserApiInfoHandler(serverCtx),
			},
			{
				// 将模型设为默认模型
				Method:  http.MethodPost,
				Path:    "/user/api/set_default",
				Handler: user.SetDefaultModelHandler(serverCtx),
			},
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
