// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package user_tenant

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTenantFieldNames          = builder.RawFieldNames(&UserTenant{})
	userTenantRows                = strings.Join(userTenantFieldNames, ",")
	userTenantRowsExpectAutoSet   = strings.Join(stringx.Remove(userTenantFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userTenantRowsWithPlaceHolder = strings.Join(stringx.Remove(userTenantFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserTenantIdPrefix = "cache:userTenant:id:"
)

type (
	userTenantModel interface {
		Insert(ctx context.Context, data *UserTenant) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UserTenant, error)
		Update(ctx context.Context, data *UserTenant) error
		Delete(ctx context.Context, id string) error
	}

	defaultUserTenantModel struct {
		sqlc.CachedConn
		table string
	}

	UserTenant struct {
		Id          string    `db:"id"`           // 记录ID
		UserId      string    `db:"user_id"`      // 用户ID
		TenantId    string    `db:"tenant_id"`    // 租户ID
		Role        string    `db:"role"`         // 角色: UserTenantRole
		InvitedBy   string    `db:"invited_by"`   // 邀请人ID
		Status      int64     `db:"status"`       // 状态: 0-废弃, 1-有效
		CreatedTime int64     `db:"created_time"` // 创建时间戳(ms)
		UpdatedTime int64     `db:"updated_time"` // 更新时间戳(ms)
		CreatedDate time.Time `db:"created_date"` // 创建日期
		UpdatedDate time.Time `db:"updated_date"` // 更新日期
	}
)

func newUserTenantModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserTenantModel {
	return &defaultUserTenantModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_tenant`",
	}
}

func (m *defaultUserTenantModel) Delete(ctx context.Context, id string) error {
	userTenantIdKey := fmt.Sprintf("%s%v", cacheUserTenantIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userTenantIdKey)
	return err
}

func (m *defaultUserTenantModel) FindOne(ctx context.Context, id string) (*UserTenant, error) {
	userTenantIdKey := fmt.Sprintf("%s%v", cacheUserTenantIdPrefix, id)
	var resp UserTenant
	err := m.QueryRowCtx(ctx, &resp, userTenantIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTenantRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTenantModel) Insert(ctx context.Context, data *UserTenant) (sql.Result, error) {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动填充时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()
	nowUnix := now.UnixMilli()
	// 直接赋值 int64，不需要 sql.NullInt64
	data.CreatedTime = nowUnix
	data.UpdatedTime = nowUnix

	// 直接赋值 time.Time，不需要 sql.NullTime
	data.CreatedDate = now
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	userTenantIdKey := fmt.Sprintf("%s%v", cacheUserTenantIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userTenantRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.TenantId, data.Role, data.InvitedBy, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate)
	}, userTenantIdKey)
	return ret, err
}

func (m *defaultUserTenantModel) Update(ctx context.Context, data *UserTenant) error {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动更新时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()

	// 直接赋值，Update 操作只需更新 update_xxx 字段
	data.UpdatedTime = now.UnixMilli()
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	userTenantIdKey := fmt.Sprintf("%s%v", cacheUserTenantIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userTenantRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.TenantId, data.Role, data.InvitedBy, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate, data.Id)
	}, userTenantIdKey)
	return err
}

func (m *defaultUserTenantModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserTenantIdPrefix, primary)
}

func (m *defaultUserTenantModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTenantRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserTenantModel) tableName() string {
	return m.table
}
