// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package knowledge_document

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeDocumentFieldNames          = builder.RawFieldNames(&KnowledgeDocument{})
	knowledgeDocumentRows                = strings.Join(knowledgeDocumentFieldNames, ",")
	knowledgeDocumentRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeDocumentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeDocumentRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeDocumentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKnowledgeDocumentIdPrefix = "cache:knowledgeDocument:id:"
)

type (
	knowledgeDocumentModel interface {
		Insert(ctx context.Context, data *KnowledgeDocument) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*KnowledgeDocument, error)
		Update(ctx context.Context, data *KnowledgeDocument) error
		Delete(ctx context.Context, id string) error
	}

	defaultKnowledgeDocumentModel struct {
		sqlc.CachedConn
		table string
	}

	KnowledgeDocument struct {
		Id              string         `db:"id"`                // UUID v7
		KnowledgeBaseId string         `db:"knowledge_base_id"` // 所属知识库ID
		DocName         sql.NullString `db:"doc_name"`          // 文档名称
		DocType         string         `db:"doc_type"`          // 类型: pdf/word/txt/md
		DocSize         int64          `db:"doc_size"`          // 大小(字节)
		Description     sql.NullString `db:"description"`       // 描述
		StoragePath     sql.NullString `db:"storage_path"`      // 存储路径(MinIO)
		SourceType      string         `db:"source_type"`       // 来源: local/url
		CreatedBy       string         `db:"created_by"`        // 上传者ID
		TokenNum        int64          `db:"token_num"`         // Token数
		ChunkNum        int64          `db:"chunk_num"`         // 分片数
		Progress        float64        `db:"progress"`          // 处理进度(0-1)
		ProgressMsg     sql.NullString `db:"progress_msg"`      // 进度/错误信息
		ProcessBeginAt  sql.NullTime   `db:"process_begin_at"`  // 开始处理时间
		ProcessDuration float64        `db:"process_duration"`  // 处理耗时(s)
		RunStatus       string         `db:"run_status"`        // 状态: pending/running/success/fail/paused
		Status          int64          `db:"status"`            // 状态: 1-有效, 0-删除/禁用
		ParserId        string         `db:"parser_id"`         // 解析器ID,目前仅支持 general | resume
		ParserConfig    string         `db:"parser_config"`     // 解析配置(JSON)
		CreatedTime     int64          `db:"created_time"`      // 创建时间戳(ms)
		UpdatedTime     int64          `db:"updated_time"`      // 更新时间戳(ms)
		CreatedDate     time.Time      `db:"created_date"`      // 创建日期
		UpdatedDate     time.Time      `db:"updated_date"`      // 更新日期
		MetaFields      sql.NullString `db:"meta_fields"`       // 元数据
	}
)

func newKnowledgeDocumentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultKnowledgeDocumentModel {
	return &defaultKnowledgeDocumentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`knowledge_document`",
	}
}

func (m *defaultKnowledgeDocumentModel) Delete(ctx context.Context, id string) error {
	knowledgeDocumentIdKey := fmt.Sprintf("%s%v", cacheKnowledgeDocumentIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, knowledgeDocumentIdKey)
	return err
}

func (m *defaultKnowledgeDocumentModel) FindOne(ctx context.Context, id string) (*KnowledgeDocument, error) {
	knowledgeDocumentIdKey := fmt.Sprintf("%s%v", cacheKnowledgeDocumentIdPrefix, id)
	var resp KnowledgeDocument
	err := m.QueryRowCtx(ctx, &resp, knowledgeDocumentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeDocumentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeDocumentModel) Insert(ctx context.Context, data *KnowledgeDocument) (sql.Result, error) {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动填充时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()
	nowUnix := now.UnixMilli()
	// 直接赋值 int64，不需要 sql.NullInt64
	data.CreatedTime = nowUnix
	data.UpdatedTime = nowUnix

	// 直接赋值 time.Time，不需要 sql.NullTime
	data.CreatedDate = now
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	knowledgeDocumentIdKey := fmt.Sprintf("%s%v", cacheKnowledgeDocumentIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, knowledgeDocumentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.KnowledgeBaseId, data.DocName, data.DocType, data.DocSize, data.Description, data.StoragePath, data.SourceType, data.CreatedBy, data.TokenNum, data.ChunkNum, data.Progress, data.ProgressMsg, data.ProcessBeginAt, data.ProcessDuration, data.RunStatus, data.Status, data.ParserId, data.ParserConfig, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate, data.MetaFields)
	}, knowledgeDocumentIdKey)
	return ret, err
}

func (m *defaultKnowledgeDocumentModel) Update(ctx context.Context, data *KnowledgeDocument) error {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动更新时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()

	// 直接赋值，Update 操作只需更新 update_xxx 字段
	data.UpdatedTime = now.UnixMilli()
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	knowledgeDocumentIdKey := fmt.Sprintf("%s%v", cacheKnowledgeDocumentIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowledgeDocumentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.KnowledgeBaseId, data.DocName, data.DocType, data.DocSize, data.Description, data.StoragePath, data.SourceType, data.CreatedBy, data.TokenNum, data.ChunkNum, data.Progress, data.ProgressMsg, data.ProcessBeginAt, data.ProcessDuration, data.RunStatus, data.Status, data.ParserId, data.ParserConfig, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate, data.MetaFields, data.Id)
	}, knowledgeDocumentIdKey)
	return err
}

func (m *defaultKnowledgeDocumentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKnowledgeDocumentIdPrefix, primary)
}

func (m *defaultKnowledgeDocumentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeDocumentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultKnowledgeDocumentModel) tableName() string {
	return m.table
}
