// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package knowledge_retrieval_log

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeRetrievalLogFieldNames          = builder.RawFieldNames(&KnowledgeRetrievalLog{})
	knowledgeRetrievalLogRows                = strings.Join(knowledgeRetrievalLogFieldNames, ",")
	knowledgeRetrievalLogRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeRetrievalLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeRetrievalLogRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeRetrievalLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgeRetrievalLogModel interface {
		Insert(ctx context.Context, data *KnowledgeRetrievalLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*KnowledgeRetrievalLog, error)
		Update(ctx context.Context, data *KnowledgeRetrievalLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultKnowledgeRetrievalLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeRetrievalLog struct {
		Id              uint64         `db:"id"`
		UserId          int64          `db:"user_id"`           // 用户唯一标识
		KnowledgeBaseId uint64         `db:"knowledge_base_id"` // 知识库ID
		Query           string         `db:"query"`             // 用户原始查询
		RetrievalMode   string         `db:"retrieval_mode"`    // 检索模式 vector/fulltext/hybrid
		RetrievalParams sql.NullString `db:"retrieval_params"`  // 检索参数快照(阈值/权重等)
		ChunkCount      int64          `db:"chunk_count"`       // 召回chunk数
		TimeCostMs      int64          `db:"time_cost_ms"`      // 查询耗时(ms)
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newKnowledgeRetrievalLogModel(conn sqlx.SqlConn) *defaultKnowledgeRetrievalLogModel {
	return &defaultKnowledgeRetrievalLogModel{
		conn:  conn,
		table: "`knowledge_retrieval_log`",
	}
}

func (m *defaultKnowledgeRetrievalLogModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKnowledgeRetrievalLogModel) FindOne(ctx context.Context, id uint64) (*KnowledgeRetrievalLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeRetrievalLogRows, m.table)
	var resp KnowledgeRetrievalLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeRetrievalLogModel) Insert(ctx context.Context, data *KnowledgeRetrievalLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, knowledgeRetrievalLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.KnowledgeBaseId, data.Query, data.RetrievalMode, data.RetrievalParams, data.ChunkCount, data.TimeCostMs)
	return ret, err
}

func (m *defaultKnowledgeRetrievalLogModel) Update(ctx context.Context, data *KnowledgeRetrievalLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowledgeRetrievalLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.KnowledgeBaseId, data.Query, data.RetrievalMode, data.RetrievalParams, data.ChunkCount, data.TimeCostMs, data.Id)
	return err
}

func (m *defaultKnowledgeRetrievalLogModel) tableName() string {
	return m.table
}
