// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package llm_factories

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	llmFactoriesFieldNames          = builder.RawFieldNames(&LlmFactories{})
	llmFactoriesRows                = strings.Join(llmFactoriesFieldNames, ",")
	llmFactoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(llmFactoriesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	llmFactoriesRowsWithPlaceHolder = strings.Join(stringx.Remove(llmFactoriesFieldNames, "`name`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLlmFactoriesNamePrefix = "cache:llmFactories:name:"
)

type (
	llmFactoriesModel interface {
		Insert(ctx context.Context, data *LlmFactories) (sql.Result, error)
		FindOne(ctx context.Context, name string) (*LlmFactories, error)
		Update(ctx context.Context, data *LlmFactories) error
		Delete(ctx context.Context, name string) error
	}

	defaultLlmFactoriesModel struct {
		sqlc.CachedConn
		table string
	}

	LlmFactories struct {
		Name        string         `db:"name"`         // LLM厂商名称
		Logo        sql.NullString `db:"logo"`         // 厂商Logo base64
		Tags        string         `db:"tags"`         // 尝厂商支持的模型类型: LLM(对话), Embedding(嵌入), Rerank(重排序), ASR(语音识别), TTS(语音合成), Image2Text(图片转文字), Text2Image(文字转图片), Video(视频生成)
		Rank        int64          `db:"rank"`         // 排序
		Status      int64          `db:"status"`       // 状态: 0-废弃, 1-有效
		CreatedTime int64          `db:"created_time"` // 创建时间戳(ms)
		UpdatedTime int64          `db:"updated_time"` // 更新时间戳(ms)
		CreatedDate time.Time      `db:"created_date"` // 创建日期
		UpdatedDate time.Time      `db:"updated_date"` // 更新日期
	}
)

func newLlmFactoriesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLlmFactoriesModel {
	return &defaultLlmFactoriesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`llm_factories`",
	}
}

func (m *defaultLlmFactoriesModel) Delete(ctx context.Context, name string) error {
	llmFactoriesNameKey := fmt.Sprintf("%s%v", cacheLlmFactoriesNamePrefix, name)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `name` = ?", m.table)
		return conn.ExecCtx(ctx, query, name)
	}, llmFactoriesNameKey)
	return err
}

func (m *defaultLlmFactoriesModel) FindOne(ctx context.Context, name string) (*LlmFactories, error) {
	llmFactoriesNameKey := fmt.Sprintf("%s%v", cacheLlmFactoriesNamePrefix, name)
	var resp LlmFactories
	err := m.QueryRowCtx(ctx, &resp, llmFactoriesNameKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", llmFactoriesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, name)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLlmFactoriesModel) Insert(ctx context.Context, data *LlmFactories) (sql.Result, error) {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动填充时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()
	nowUnix := now.UnixMilli()
	// 直接赋值 int64，不需要 sql.NullInt64
	data.CreatedTime = nowUnix
	data.UpdatedTime = nowUnix

	// 直接赋值 time.Time，不需要 sql.NullTime
	data.CreatedDate = now
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	llmFactoriesNameKey := fmt.Sprintf("%s%v", cacheLlmFactoriesNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, llmFactoriesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Logo, data.Tags, data.Rank, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate)
	}, llmFactoriesNameKey)
	return ret, err
}

func (m *defaultLlmFactoriesModel) Update(ctx context.Context, data *LlmFactories) error {
	// --------------------------------------------------------------------------------
	// [AUTO-FILL] 自动更新时间 (NOT NULL 版本)
	// --------------------------------------------------------------------------------
	now := time.Now()

	// 直接赋值，Update 操作只需更新 update_xxx 字段
	data.UpdatedTime = now.UnixMilli()
	data.UpdatedDate = now
	// --------------------------------------------------------------------------------

	llmFactoriesNameKey := fmt.Sprintf("%s%v", cacheLlmFactoriesNamePrefix, data.Name)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `name` = ?", m.table, llmFactoriesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Logo, data.Tags, data.Rank, data.Status, data.CreatedTime, data.UpdatedTime, data.CreatedDate, data.UpdatedDate, data.Name)
	}, llmFactoriesNameKey)
	return err
}

func (m *defaultLlmFactoriesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLlmFactoriesNamePrefix, primary)
}

func (m *defaultLlmFactoriesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", llmFactoriesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLlmFactoriesModel) tableName() string {
	return m.table
}
